"""Enrich all scholar profiles with web-researched 5-paragraph essays.

Each profile follows WRITING_TEMPLATES.md scholar template:
1. Identity and credentials
2. Intellectual formation and approach
3. Contributions to Maier studies
4. Key arguments
5. Relevance to this site
"""
import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'db', 'atalanta.db')

PROFILES = {

"H.M.E. de Jong": """Helena Maria Elisabeth De Jong was a Dutch art historian who completed her doctoral dissertation on Michael Maier's Atalanta Fugiens at the University of Utrecht in 1965, publishing it in Dutch as Michael Maier's Atalanta Fugiens: Bronnen van een alchemistisch emblemenboek. The expanded English edition, published by E.J. Brill in Leiden in 1969, remains the foundational study of Maier's emblem book and the single most important work in Atalanta Fugiens scholarship. De Jong's interest in iconology led her from conventional art history into the study of alchemical emblems, where she discovered a field requiring expertise in classical philology, medieval textual traditions, and the history of science alongside visual analysis.

De Jong's method was source-critical in the tradition of Dutch art history: systematic, archival, and exhaustive. Rather than offering a general interpretation of Maier's alchemical philosophy or a psychological reading in the Jungian mode, she set out to identify the precise textual sources behind each of the fifty emblems. For every motto, discourse argument, and iconographic motif, De Jong traced the specific passages in the Turba Philosophorum, the Rosarium Philosophorum, the Aurora Consurgens, the Pseudo-Aristotelian Tractatulus, Ovid's Metamorphoses, and dozens of other classical and alchemical texts that Maier quoted, paraphrased, or transformed. This source-critical approach was unprecedented in alchemical scholarship, which had previously treated emblem books as self-contained artistic or mystical statements rather than as compilations with traceable textual genealogies.

De Jong's central discovery was that Maier was not an original alchemical theorist but a supremely learned compiler and re-interpreter of inherited traditions. She demonstrated that virtually every element of the Atalanta Fugiens can be traced to identifiable passages in the medieval and Renaissance alchemical corpus. The Turba Philosophorum emerges as Maier's single most prolific source (contributing nine mottos), followed by the Rosarium Philosophorum, the Tabula Smaragdina, and the Allegoria Merlini. De Jong mapped these source relationships emblem by emblem, creating a concordance that reveals the architecture of Maier's extraordinary erudition. As the RIDE review of Furnace and Fugue noted in 2023, De Jong's 1969 study "remains the only substantive scholarly examination of Maier's text" more than half a century after its publication.

Perhaps De Jong's most distinctive intellectual contribution is her demonstration that alchemical terms operate simultaneously across multiple registers: material (laboratory operations), medical (humoral pathology), spiritual (psychological transformation), and cosmological (planetary correspondences). She showed that a concept like Nigredo carries meaning as a chemical process (blackening through putrefaction), a medical condition (saturnine melancholia), a spiritual state (the dark night of the soul), and a cosmological principle (Saturn's dominion over prima materia). This multi-register model has become the standard framework for understanding alchemical symbolism and has influenced scholars across disciplines.

This site is fundamentally a showcase of De Jong's findings. Every emblem page's source analysis, every dictionary term's alchemical significance, every source authority identification, and the multi-register definitions all derive from her meticulous scholarship. Without De Jong's work, the textual traditions behind the Atalanta Fugiens would remain opaque to modern readers, and the systematic connections between Maier's emblems and their medieval antecedents would be invisible.""",

"Hereward Tilton": """Hereward Tilton is a lecturer in the Department of Studies in Religion at the University of Queensland, Brisbane, Australia. His monograph The Quest for the Phoenix: Spiritual Alchemy and Rosicrucianism in the Work of Count Michael Maier (1569-1622), published by Walter de Gruyter in 2003 as volume 88 of the Arbeiten zur Kirchengeschichte series, originated as a doctoral thesis at the University of Queensland in 2002. It represents the most comprehensive modern study of Maier's intellectual world, placing the entire body of Maier's work within the broader context of early modern Rosicrucianism, spiritual alchemy, and the political dynamics of the late Habsburg Empire.

Tilton's approach is historiographical and contextual, drawing on extensive archival research and engagement with the scholarly literature on Rosicrucianism developed by Carlos Gilly and the Bibliotheca Philosophica Hermetica in Amsterdam. Where De Jong focused narrowly on the textual sources of the Atalanta Fugiens, Tilton reads Maier's full bibliography of approximately twenty-five published works as a coherent intellectual project, charting the development of his Hermetic worldview through his service at the courts of Rudolf II and Moritz von Hessen-Kassel. Tilton explicitly critiques Carl Jung's psychological interpretation of alchemy, arguing instead for a spiritual alchemy grounded in Aristotelian elemental transmutation and the prisca sapientia tradition of perennial wisdom.

Tilton's most significant contribution to Maier biography was his correction of the birth year from 1568 to 1569, based on the De Medicina Regia manuscript discovered by Karin Figala and Ulrich Neumann in Munich. He established key biographical facts including Maier's father's profession as a gold embroiderer (Goldsicker) serving Danish and Holstein nobility, Maier's claim to have produced the Universal Medicine during his Kiel laboratory period (1602-1608), and the economic precariousness of his position as an unlanded nobleman after Rudolf II's ennoblement. Tilton frames Maier's death in Magdeburg (1622) against the backdrop of the Thirty Years' War, reading the phoenix motif in Maier's final works as an allegory of spiritual death and rebirth.

Tilton argues that Maier was not merely sympathetic to Rosicrucianism but actively sought to define authentic Rosicrucianism on his own terms, distinguishing genuine natural philosophy from imposture through works like the Silentium post Clamores and Themis Aurea. He challenges both reductive laboratory readings and purely Jungian symbolic approaches, positioning Maier within the prisca sapientia tradition — the belief in a perennial philosophy transmitted from Hermes Trismegistus through the mystery schools of antiquity to the Rosicrucian Brotherhood. The Atalanta Fugiens, in Tilton's reading, is both an alchemical textbook and a vehicle for this Hermetic worldview, deliberately deploying multimedia pedagogy (image, text, music) to engage the whole person in the pursuit of natural knowledge.

For this site, Tilton's work provides the biographical and intellectual-historical framework within which De Jong's source-critical findings are situated. His scholarly references enrich the commentary on fifteen emblems, his biographical research informs the biography page, and his argument about Maier's cosmology (neither geocentric nor heliocentric, but a hybrid system based on Rothmann) adds a dimension to the astronomical references in the emblem discourses.""",

"J.B. Craven": """The Reverend J.B. Craven, D.D., was a Scottish clergyman and antiquarian from Kirkwall, Orkney, whose Count Michael Maier, Doctor of Philosophy and of Medicine, Alchemist, Rosicrucian, Mystic, 1568-1622, published by William Peace and Son in 1910, was the first English-language monograph on Maier. It remained the sole book-length study for over half a century until De Jong's dissertation in 1965, and Joscelyn Godwin described it as late as 1999 as "still indispensable for anyone without a complete set of Maier's works on their shelves." A facsimile edition was issued by Dawson's of Pall Mall in London in 1968.

Craven's approach was that of a Victorian antiquarian: exhaustive in scope, encyclopedic in aspiration, and reverential toward his subject. Writing at a time when few of Maier's approximately twenty-five published works had been studied in any detail by modern scholars, Craven undertook the task of surveying, describing, and summarizing Maier's entire output, providing English-language paraphrases of the Latin texts and detailed descriptions of the engravings. His method was primarily descriptive rather than analytical — he did not attempt the kind of source criticism that De Jong would later perform, nor did he situate Maier within the broader intellectual movements that Tilton would illuminate. Nevertheless, the comprehensiveness of his catalog made it the standard reference for generations of readers.

Craven's most valuable specific contribution is his detailed verbal description of the Atalanta Fugiens frontispiece, which remains one of the most precise accounts of the engraving's iconographic program. He identifies and describes the race of Atalanta and Hippomenes at the bottom, Venus handing the golden apples at the side, the couple embracing in Cybele's temple entrance before emerging as lion and lioness, and Hercules approaching the tree of the Hesperides above. He also provides extensive biographical detail and bibliographic descriptions of Maier's other works, including the Symbola Aureae Mensae, the Viatorium, and the Themis Aurea.

Craven's treatment of alchemical content is sympathetic but uncritical by modern standards — he accepts Maier's claims largely at face value and does not distinguish between different levels of textual authority or interpretive confidence. His discussions of individual emblems tend toward paraphrase rather than interpretation, reproducing Maier's arguments without interrogating their sources or situating them within the broader alchemical tradition. His religious sympathy with Maier as a "Rosicrucian Mystic" reflects early twentieth-century esoteric interests rather than academic historiography.

For this site, Craven provides survey-level scholarly references for seventeen emblems and the frontispiece. His biographical detail supplements the archivally grounded reconstructions of Tilton and Godwin, and his frontispiece description informs the visual analysis of Emblem 0. He remains a useful starting point for English-language readers approaching Maier for the first time.""",

"Joscelyn Godwin": """Joscelyn Godwin (born 16 January 1945, Kelmscott, Oxfordshire) is a musicologist, historian of esotericism, and translator. Educated as a chorister at Christ Church Cathedral School, Oxford, then at Radley College (Music Scholar), and Magdalene College, Cambridge, he came to the United States in 1966 for graduate work in musicology at Cornell University (Ph.D., 1969). He taught at Colgate University in Hamilton, New York, from 1971 until his retirement in 2016 as Professor of Music Emeritus. Johann F.W. Hasler has described him as "without any doubt the leading authority on the historical study of speculative music."

Godwin occupies a unique position in Maier scholarship as both the editor of the standard English edition of the Atalanta Fugiens and the author of the most detailed English-language biographical essay on Maier. His edition, Michael Maier, Atalanta Fugiens: An Edition of the Fugues, Emblems, and Epigrams, with an introductory essay by Hildemarie Streich, was published by Magnum Opus Hermetic Sourceworks in 1987 and later by Phanes Press (1989). It included the first complete recording of the fifty fugues, performed by Rachel Platt, Emily Van Evera, Rufus Muller, and Richard Wistreich, later remastered on CD by Claudio Records. A Spanish edition, La Fuga de Atalanta, was published by Ediciones Atalanta in 2007. His edition made the musical dimension of the work accessible to modern performers and scholars for the first time, revealing a level of compositional sophistication that most literary and art-historical scholarship had overlooked.

Godwin's biographical essay, "The Deepest of the Rosicrucians: Michael Maier," published in The Rosicrucian Enlightenment Revisited (1999), draws extensively on the archival discoveries of Karin Figala and Ulrich Neumann to reconstruct Maier's life with unprecedented detail. He established key facts including Maier's birth in Kiel in 1569, his father Peter's profession as a gold embroiderer, his claim to have produced the Universal Medicine "of a bright lemon color" during the Kiel laboratory period, and the paradox of his position as an unlanded nobleman — ennobled by Rudolf II but left without income, "forced into a kind of upper-class beggary." Godwin identified Maier's five-year English sojourn (1611-1616) as "almost certainly the fulfilment of a diplomatic mission" preparing the Frederick-Elizabeth dynastic marriage.

Godwin characterizes Maier's creative method as distinctively multimedia — visible from the Rose-Cross Christmas greeting to James I (1611), with its combination of gold-and-red word-emblem, four Latin poems, and six-part musical canon, through to the Atalanta Fugiens itself with its integrated program of image, text, and music. His musicological training gives him a sensitivity to the fugues' modal structures, text-painting devices, and contrapuntal technique that no other Maier scholar brings. His article "Musical Alchemy: the Work of Composer and Listener" (Temenos, 1985) and "A Background for Michael Maier's Atalanta Fugiens" (Hermetic Journal, 1985) explore the theoretical foundations of Maier's musical-alchemical synthesis.

For this site, Godwin's biographical research enriches the biography page with archival detail unavailable from any other English-language source. His edition of the fugues is the standard reference for the musical dimension, and his characterization of Maier's multimedia pedagogy informs the frontispiece discussion and the site's overall interpretive framework.""",

"Peter J. Forshaw": """Peter J. Forshaw is Universitair Docent (Senior Lecturer) for History of Western Esotericism in the Early Modern Period at the Center for History of Hermetic Philosophy and Related Currents (GHF), University of Amsterdam. He studied Sanskrit, Tibetan, and Indian Philosophy at SOAS, University of London (1982-86), then took an MA in Renaissance Studies at Birkbeck, University of London, where he completed his doctorate on the interplay of alchemy, magic, and cabala in Heinrich Khunrath's Amphitheatrum Sapientiae Aeternae. He serves as editor-in-chief of Aries: The Journal for the Study of Western Esotericism, published by Brill.

Forshaw's primary contribution to Maier scholarship is his identification and analysis of "mytho-alchemy" as a distinct genre of alchemical writing. His essay "Michael Maier and Mythoalchemy," published in the Furnace and Fugue digital edition (University of Virginia Press, 2020), argues that the literary genre of hermetic mythology "worked on the premise that the myths of Egyptian, Greek, and Latin antiquity were repositories of alchemical secrets, coded narratives of natural philosophy." Forshaw traces this tradition from medieval Arabic and Latin precursors through to its flowering in Maier's emblematic oeuvre, identifying the Arcana Arcanissima (1614) — not the visually spectacular Atalanta Fugiens — as the foundational text of Maier's mytho-alchemical project.

In his Infinite Fire webinar for the Ritman Library (2012), Forshaw provides the most accessible scholarly introduction to the AF emblems available, walking through individual engravings while revealing structural features overlooked by other scholars. He demonstrates that Maier organizes each emblem's discourse around the four disciplines of the medieval quadrivium — arithmetic, music, geometry, and astronomy — systematically mapping every alchemical concept across all four mathematical sciences. He identifies sources not noted by De Jong, including Horapollo's Hieroglyphica as a model for Emblem XXVII's impossibility motif, Ficino's De Vita Libri Tres as a source for Emblem IX's rejuvenation imagery, and Khalid ibn Yazid's Kitab al-Thalath Kalimat for the gestation metaphor in Emblem I.

Forshaw is emphatic on two points that distinguish his reading from both spiritual-alchemical and Jungian interpretations. First, Maier is "not Paracelsian" — the AF works exclusively with the Mercury-Sulphur dyad without the Tria Prima. Second, Maier preferred the term "chemical" over "alchemical" and explicitly described his work as natural rather than supernatural. At the same time, Forshaw acknowledges "parallel processing" in Maier's thought — an awareness that alchemical purification mirrors the sublimation of the gross human being toward refined moral and spiritual states — but insists that the primary register of the text is laboratory chemistry and natural philosophy.

For this site, Forshaw's mytho-alchemical framework provides the interpretive context for every emblem that draws on Greek or Egyptian mythology. His quadrivium analysis reveals an organizational principle that enriches the discourse summaries, and his identification of overlooked sources (Horapollo, Ficino, Khalid ibn Yazid) adds precision to the source analysis on several emblem pages. His published article "Laboratorium, Auditorium, Oratorium" is the key reference for the alchemical-musical dimension of the work.""",

"Walter Pagel": """Walter Pagel (1898-1983) was a German-born British pathologist and historian of medicine, the youngest son of Julius Pagel, Professor of Medical History at the Friedrich Wilhelms Universitat in Berlin. Pagel trained in pathology at the Municipal Hospital Am Friedrichshain in Berlin and later at Tubingen University, but the majority of his historical research was conducted after his retirement from pathology in 1967. He became one of the most important historians of early modern medicine in the twentieth century, with major works on Paracelsus, William Harvey, and Jan Baptista van Helmont that transformed understanding of the relationship between alchemy, medicine, and natural philosophy.

Pagel's monograph Paracelsus: An Introduction to Philosophical Medicine in the Era of the Renaissance (S. Karger, 1958; revised 2nd edition 1982) established the standard scholarly framework for understanding Paracelsian iatrochemistry. His William Harvey's Biological Ideas (1967) and Johann Baptista van Helmont: Reformer of Science and Medicine (1982) further demonstrated that the boundaries between alchemy and legitimate natural philosophy were far more permeable in the early modern period than later historians had assumed. Pagel's scholarship was pivotal in situating Paracelsus and his followers within the broader intellectual traditions of Renaissance Neoplatonism, Gnosticism, and Hermetic philosophy.

Pagel's contribution to Atalanta Fugiens scholarship consists of his review of De Jong's 1969 monograph, published in Medical History (1973). This review brought the perspective of a practicing pathologist and historian of medicine to bear on Maier's emblems, foregrounding the iatrochemical and Empedoclean dimensions that De Jong's art-historical approach had noted but not fully developed. Pagel identified specific emblems where the medical register of alchemical symbolism is particularly prominent, drawing attention to the humoral medicine in Emblem XXVIII (the steam bath as therapeutic purification), the Empedoclean cosmology underlying Emblem X, and the medical analogies in Emblems II, XIII, XVI, and XLVIII.

Pagel's most distinctive argument is that Maier's training as a physician was not incidental to his alchemical work but foundational to it. The medical register in the AF emblems is not merely a metaphor borrowed from medicine to describe chemical processes — it reflects a genuine theoretical framework within which Maier understood both bodily health and metallic transformation as expressions of the same natural principles. This insight has become particularly important for the multi-register model of alchemical terms developed on this site, where the "medical" register entries owe a significant intellectual debt to Pagel's identification of humoral and iatrochemical themes.

For this site, Pagel provides twelve emblem-specific scholarly references that ground the medical dimension of Maier's emblematic program in the history of early modern medicine. His perspective is essential for understanding why a physician would write an alchemical emblem book, and how the language of disease, cure, purgation, and restoration functions not as decorative analogy but as a parallel explanatory system.""",

"Paul Miner": """Paul Miner is a literary historian and iconographer whose article "Blake and Atalanta Fugiens: Two Plates, Three Conjectures," published in Notes and Queries (2012), investigates the visual influence of Maier's Merian-engraved plates on the art of William Blake. Miner's work opens a reception-history dimension largely absent from other Atalanta Fugiens scholarship, which has focused overwhelmingly on Maier's sources rather than his influence on later artistic and intellectual traditions.

Miner's approach is comparative iconographic analysis, placing specific Blake designs alongside the corresponding AF engravings to identify compositional borrowings, shared motifs, and transformed symbolic elements. He does not engage with Maier's alchemical philosophy directly but with the visual afterlife of the Atalanta Fugiens plates — a question that connects Maier's seventeenth-century emblems to the broader history of Hermetic visual culture in English Romanticism. His method requires demonstrating not merely thematic similarity (both artists depict hermaphrodites, for instance) but specific compositional parallels that imply direct knowledge of the source images.

Miner identifies four emblem-specific iconographic connections between Blake and the Atalanta Fugiens. He focuses particularly on the Hermaphrodite lying in darkness (Emblems XXXIII and XXXIV) and the standing Hermaphrodite born of two mountains (Emblem XXXVIII), arguing that Blake's hermaphroditic and hierogamic imagery — the union of contraries that is central to Blake's mature mythology in works like Jerusalem and The Marriage of Heaven and Hell — draws compositionally on Maier's visual formulations. The argument is strengthened by the fact that Blake is known to have had access to alchemical source material through his patrons and associates.

Miner's work demonstrates that the Atalanta Fugiens was not merely a period curiosity but a visual resource that continued to shape artistic production nearly two centuries after its publication. His reception-history approach complements De Jong's backward-looking source analysis with a forward-looking study of influence and transmission.

For this site, Miner provides four emblem-specific references and a unique perspective on the cultural afterlife of Maier's images. His work supports the argument that the AF plates, as engraved by Merian, possess an aesthetic power that transcends their original alchemical function.""",

"Douglas Leedy": """Douglas Leedy (1938-2015) was an American composer, conductor, and musicologist who specialized in early music performance practice, alternative tuning systems, and the intersection of music with cosmological and philosophical traditions. His compositional work drew on ancient Greek and Asian musical systems, and he was known for performances and recordings of music in just intonation and other non-standard tuning systems.

Leedy's contribution to Atalanta Fugiens scholarship consists of his review of Joscelyn Godwin's 1987 edition, published in Notes: Quarterly Journal of the Music Library Association (1991). This review provides the only sustained technical musicological assessment of Maier's fifty three-voice fugues in our corpus, evaluating them as compositions rather than as alchemical symbols or historical curiosities. Leedy brought to this analysis decades of experience with Renaissance and early Baroque polyphonic practice, giving him a sensitivity to the musical idiom of Maier's period that few other AF scholars possess.

Leedy's most important observation is that the fugues are musically sophisticated compositions that reward careful analysis, challenging the dismissive view — common in both musicological and alchemical scholarship — that they are crude or amateurish. He identifies modal choices that correspond to the alchemical content of specific emblems, text-painting techniques where the musical lines mirror allegorical actions, and structural features suggesting genuine compositional skill on the part of Maier or an unidentified collaborator.

For this site, Leedy validates the musical dimension of the Atalanta Fugiens as worthy of serious scholarly attention and provides the technical vocabulary for discussing the fugues' relationship to the emblematic program. His assessment that Maier's musical writing is "not without a certain pleasure" — echoing Maier's own subtitle — supports the site's treatment of the fugues as integral rather than decorative elements of the multi-sensory work.""",

"Pamela H. Smith": """Pamela H. Smith is the Seth Low Professor of History at Columbia University, founding Director of the Center for Science and Society, and principal investigator of the Making and Knowing Project. She is one of the most influential historians of early modern science working today, with major works including The Business of Alchemy: Science and Culture in the Holy Roman Empire (Princeton, 1994), The Body of the Artisan: Art and Experience in the Scientific Revolution (Chicago, 2004), and From Lived Experience to the Written Word: Reconstructing Practical Knowledge in the Early Modern World (2022). She received the Herzog August Bibliothek international prize for Cultural History and the History of Knowledge in 2023.

Smith's approach to alchemy is rooted in the history of material culture and artisanal knowledge. Her central argument — developed across multiple books and the Making and Knowing Project — is that early modern natural knowledge was produced not only through reading and reasoning but through bodily engagement with materials in workshops and laboratories. This materialist perspective reframes alchemy not as a pseudoscience or mystical pursuit but as a legitimate form of artisanal inquiry into the properties and transformations of matter.

Smith's engagement with the Atalanta Fugiens comes through her review in Medical History (2009) of Thomas Hofmeier's German translation and edition (Chymisches Cabinet, 2008), based on the 1708 German edition. She reads Maier's emblems not merely as symbolic puzzles but as representations of actual craft practices — smelting, distilling, washing, firing — that encode genuine chemical knowledge. The 1708 German edition's continued circulation demonstrates the work's practical relevance nearly a century after its original publication, evidence that it was consulted by working practitioners as well as intellectual adepts.

For this site, Smith's materialist perspective provides an essential counterpoint to purely textual and symbolic readings. Her emphasis on the practical, artisanal dimension of Maier's emblems enriches the discussion of emblems depicting specific craft processes — the washerwoman of Emblem III, the potter of Emblem XV, the steam bath of Emblem XXVIII — where the visual depiction of labor is not merely allegorical but draws on observable workshop practices. Her Making and Knowing Project at Columbia represents the most ambitious contemporary effort to reconstruct the kind of hands-on experimental knowledge that Maier both practiced and described.""",

"Donna Bilak": """Donna Bilak is an independent scholar of early modern visual culture, currently affiliated with NYU's Gallatin School of Individualized Study and formerly at the Pratt Institute. Her research centers on steganography, visual cryptography, and the hidden codes embedded in early modern alchemical imagery. Her doctoral work and subsequent postdoctoral research at the Science History Institute (then the Chemical Heritage Foundation) focused on Michael Maier's Atalanta Fugiens as a steganographic object — an artifact that conceals messages within its visual and structural design, accessible only to readers trained in the conventions of alchemical and mathematical reading.

Bilak co-edited Furnace and Fugue: A Digital Edition of Michael Maier's Atalanta fugiens (1618) with Scholarly Commentary (University of Virginia Press, 2020) with Tara Nummedal. The project, developed through Brown University Library's Digital Publications Initiative with Mellon Foundation support, won the 2022 Roy Rosenzweig Prize for Creativity in Digital History from the American Historical Association — the most prestigious award in digital humanities. It represents the first born-digital scholarly edition of the Atalanta Fugiens, featuring fully searchable text in Latin, German, and English, high-resolution zoomable images, newly commissioned vocal recordings, and interactive tools for exploring the multi-layered structure of each emblem.

Bilak's central contribution is her essay "Chasing Atalanta: Maier, Steganography, and the Secrets of Nature," which proposes that Maier engineered the Atalanta Fugiens as a work of steganography concealing a magic square within its structure. She argues that the fifty sequential emblems can be rearranged according to a mathematical grid whose rows, columns, and diagonals encode hidden relationships — a virtuoso act of concealment that exploits the inherent duality of the emblem form (which simultaneously reveals and conceals meaning). Her analysis identifies patterns of "doubling" — binary pairs and mirror structures — that facilitate exploration of transformation as a central trope.

Bilak's steganographic approach extends beyond the conventional reading of alchemical symbolism (recognizing that a toad represents sulphur, for instance) to propose that the plates contain a second structural layer encoded in formal properties: spatial relationships, geometric proportions, and the sequential ordering of the emblems themselves. This goes further than De Jong's source-critical method into questions of mathematical design and intentional concealment.

For this site, Bilak's work represents the cutting edge of Atalanta Fugiens scholarship. The Furnace and Fugue digital edition is the primary alternative resource for studying the work in its multimedia fullness, and her steganographic thesis poses questions about the depth of Maier's compositional planning that have yet to be fully explored.""",

"Tara Nummedal": """Tara Nummedal is the John Nickoll Provost's Professor of History and Professor of Italian Studies at Brown University. She is a historian of early modern alchemy, fraud, and entrepreneurship whose work has reshaped understanding of alchemy's place in the economic, legal, and social history of early modern Europe. Her monograph Alchemy and Authority in the Holy Roman Empire (University of Chicago Press, 2007) demonstrates that alchemical practitioners operated within complex networks of patronage, investment, and legal regulation — the same networks that shaped Maier's career as he moved from Rudolf II's court through England to Moritz von Hessen's household.

Nummedal co-edited Furnace and Fugue: A Digital Edition of Michael Maier's Atalanta fugiens with Scholarly Commentary (University of Virginia Press, 2020) with Donna Bilak, a project that won the 2022 Roy Rosenzweig Prize for Creativity in Digital History from the American Historical Association. The project was the first digital publication produced by Brown University Digital Publications, a signature program within Brown's Center for Digital Scholarship launched with Andrew W. Mellon Foundation funding. Nummedal was appointed Faculty Director of Brown's Center for Digital Scholarship in July 2023.

The Furnace and Fugue project emerged from Nummedal's recognition that modern disciplinary boundaries have fractured the wide-ranging expertise a seventeenth-century reader would have needed to engage with Maier's multimedia work. The editors convened historians of science, music, mathematics, and art alongside rare book curators and professional singers to produce a collaborative digital edition that allows readers to hear, see, manipulate, and investigate the Atalanta Fugiens in ways that Maier may have imagined but that were technically impossible before digital publication. The edition features interactive tools for comparing text, image, and music side by side, and includes a manipulable performance space where users can curate their own selections and arrangements.

Nummedal's broader scholarly contribution to understanding Maier lies in her contextual work on alchemy and authority. Her research demonstrates that the line between legitimate and fraudulent alchemy was constantly negotiated in early modern courts, and that practitioners like Maier operated in a precarious space between patronage and prosecution. This perspective illuminates Maier's careful self-presentation through his published works, his strategic dedications to Protestant rulers, and his insistence on chemical (not alchemical) terminology.

For this site, Nummedal's work provides the institutional model for digital humanities engagement with the Atalanta Fugiens. The Furnace and Fugue project is the primary alternative digital resource, and its collaborative methodology — bringing together scholars from multiple disciplines to address a multimedia work — has influenced this project's own interdisciplinary approach.""",

"Catherine Morris Wescott": """Catherine Morris Wescott is a scholar of music and alchemy whose analysis of the Atalanta Fugiens fugues, published in the AthanorX journal, provides the most technically detailed examination of Maier's musical compositions in our corpus. Her work uniquely combines musicological analysis with alchemical interpretation, reading the fifty three-voice fugues not merely as musical settings of the epigram texts but as sonic encodings of alchemical processes.

Wescott's approach brings together music theory (modal analysis, interval identification, cantus firmus technique, text-painting) with the alchemical symbolism of the emblem tradition. She demonstrates that Maier's modal choices — Dorian, Phrygian, Mixolydian, and others — correspond to planetary associations established in classical and medieval music theory (Saturn, Mars, Jupiter) that in turn relate to the specific alchemical stages and metals depicted in each emblem's plate. This systematic correspondence between mode, planet, and alchemical operation suggests a level of compositional intentionality that goes beyond conventional text-setting.

Wescott's most detailed analyses concern Emblems XXIV, XXVIII, XXXI, and XLIV, where she combines musical and iconographic readings to show how the three voices of each fugue — typically representing Atalanta (soprano), Hippomenes (tenor), and the golden apple (cantus firmus) — enact the alchemical drama of pursuit, fixation, and transformation. She identifies the cantus firmus as the structural anchor derived from liturgical chant, around which the two pursuing voices weave their contrapuntal dialogue. Her analysis of the planetary-modal correspondences in these emblems reveals how the musical dimension reinforces the visual and textual content rather than merely accompanying it.

For this site, Wescott provides fifteen scholarly references spanning both musical and alchemical interpretation. Her work is essential for anyone seeking to understand the fugues as integral components of Maier's emblematic program rather than decorative additions. Together with Godwin's edition and Leedy's review, Wescott's analysis forms the core of the site's engagement with the musical dimension of the Atalanta Fugiens.""",
}


def main():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    updated = 0

    for name, profile in PROFILES.items():
        result = c.execute('UPDATE scholars SET overview = ? WHERE name = ?', (profile, name))
        if result.rowcount > 0:
            paras = profile.count('\n\n') + 1
            print(f'  Updated: {name} ({len(profile)} chars, {paras} paragraphs)')
            updated += 1
        else:
            print(f'  NOT FOUND: {name}')

    conn.commit()
    conn.close()
    print(f'\nUpdated {updated}/12 scholar profiles.')


if __name__ == '__main__':
    main()
