"""
seed_definition_long.py — Populate definition_long for all 38 dictionary terms.

Synthesized from De Jong's monograph and supporting scholarship.
Updates only rows where definition_long IS NULL, preserving any manual edits.
Idempotent: safe to re-run.
"""

import sqlite3
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "db" / "atalanta.db"

# Each entry: (slug, definition_long)
DEFINITIONS = [
    (
        "adonis",
        "In classical mythology, Adonis is the beautiful youth born from the incestuous union of Myrrha and her father Cinyras, beloved by Venus and killed by a wild boar. Ancient alchemists adopted Adonis as a figure for the Philosophical Sun, distinct from the common sun in the sky, whose seasonal death and resurrection encode the dissolution and reconstitution of the solar principle in the Great Work. De Jong demonstrates that Maier treats Adonis, Dionysus, Osiris, and Sol as interchangeable names for the same alchemical reality, citing the verse 'All are equal to each other, Dionysus, Sol, and Adonis.' In Emblem XLI, Maier reads the boar's tusks as the sharp acid or dissolving liquid that wounds the Philosophical Sun, while Venus's attempt to revive Adonis and her staining of the white roses red with her blood encodes the transition from albedo to rubedo. The annual mourning and subsequent celebration described by Maier parallels the death-and-resurrection pattern that structures the entire second half of Atalanta Fugiens."
    ),
    (
        "albedo",
        "The albedo or whitening is one of the oldest conceptions in alchemy, originating in the Hellenistic period when the transmutation process was understood through the color changes observed during metalworking and dyeing. De Jong traces the alchemical whitening to ancient textile and metallurgical practice, where materials had to be thoroughly bleached before receiving the final red dye, a sequence that maps directly onto the stages of the opus. In Atalanta Fugiens, Maier distributes the albedo across multiple emblems: the laundress bleaching sheets in Emblem III, the sowing of gold in white foliated earth in Emblem VI, King Duenech's purifying steam bath in Emblem XXVIII, and the baptismal washing in Emblem XIII. De Jong shows that for Maier the whitening operates simultaneously in chemical, medical, and spiritual registers, where expelling the blackness of impure matter parallels curing the melancholy of the Saturnian temperament and cleansing the soul of sin through baptism. The Turba Philosophorum teaches that whiteness is hidden in the womb of blackness, a principle Maier dramatizes by showing that every purification requires the prior destruction of the nigredo."
    ),
    (
        "allegoria-merlini",
        "The Allegoria Merlini is a medieval Latin alchemical narrative, printed in the Artis Auriferae compilation, in which a king afflicted by a wasting disease undergoes a sequence of purgative medical treatments encoding the stages of the alchemical process. De Jong first analyzed this text in his 1964 article on Emblem XLVIII in the Netherlands Yearbook for History of Art, establishing it as one of Maier's primary sources for the King Duenech cycle. The narrative describes the king's illness as a condition of impurity requiring dissolution in water, purging of black bile, and gradual restoration through increasingly intense applications of heat, a medical allegory that Maier adapts in Emblems XXIV, XXVIII, XXXI, and XLVIII. De Jong and Pagel both emphasize the three-level correspondence in the Merlini narrative: the king's bodily cure maps onto metallurgical coction and the spiritual redemption of fallen matter. The text was widely transmitted through the compilations Artis Auriferae and Theatrum Chemicum, and its influence extends beyond Maier into the broader Rosicrucian reception of alchemical allegory."
    ),
    (
        "aqua-regia",
        "Aqua regia, the royal water composed of nitric and hydrochloric acids, held a unique position in alchemical thought as the only known solvent capable of dissolving gold, the most noble and resistant of metals. This paradoxical capacity made it a powerful symbol: the king of metals could only be overcome by the king of waters, a correspondence that alchemists read as evidence of nature's hidden symmetries. De Jong notes that Maier references aqua regia within the broader dissolution imagery of Atalanta Fugiens, where the capacity to break down even the most perfect substance is a prerequisite for reconstitution at a higher level. In the alchemical tradition transmitted through the Turba Philosophorum and the Rosarium, the concept of a universal solvent bridges the practical laboratory and the symbolic framework, since dissolution of gold is both a chemical operation and a figure for the return of perfected matter to prima materia. Maier's treatment reflects the alchemical teaching that destruction and perfection are inseparable: only the most powerful agent of dissolution can prepare the way for the most exalted product of the Work."
    ),
    (
        "aqua-vitae",
        "The aqua vitae or water of life is a polyvalent concept in alchemical literature, signifying the purified mercurial water that serves simultaneously as solvent and medicine, agent of death and instrument of resurrection. De Jong traces this double meaning to Greek alchemical writings, where Zosimos describes the divine water as the object of the entire art, the beginning and end of the Work. In the Arabic and Latin traditions transmitted through the Turba Philosophorum, the aqua vitae is the liquid in which impure metals are dissolved and from which they rise again as gold, making it both the water of destruction and the water of renewal. Maier invokes this concept in the King Duenech sequence, where the curative potion administered to the sick king encodes the elixir that heals through dissolution. De Jong demonstrates that Maier's aqua vitae imagery draws on the Merlini allegory's identification of the healing bath with baptismal water, creating a characteristically multilayered symbol that operates in chemical, medical, and sacramental registers simultaneously."
    ),
    (
        "ars-magna",
        "The Ars Magna or Great Art originated as the combinatorial philosophical system of the Catalan polymath Ramon Llull in the thirteenth century, designed to demonstrate truths about God and creation through the systematic combination of fundamental principles. Pseudo-Lullian alchemical writers adapted this framework to describe the reciprocal operations of dissolution and coagulation as complementary movements within a single unified process. De Jong identifies a connection between Emblem V and the Lullian teaching transmitted through the Harmonica Chemica, where the principle that one nature coagulates only through the dissolution of another is expressed as a logical necessity rather than merely an empirical observation. Maier's debt to the Lullian tradition appears in his insistence that the Son of Philosophy is sulphur carried in mercury, a formulation De Jong traces to Cordicillus chapter 32. The Ars Magna thus provides Atalanta Fugiens with part of its intellectual scaffolding: the conviction that alchemical transformation follows a rational combinatorial logic grounded in the structure of creation itself."
    ),
    (
        "atalanta",
        "In Ovid's Metamorphoses Book X, Atalanta is the swift-footed maiden whom no suitor can outrun until Hippomenes, aided by Venus's golden apples, distracts her from the race and wins her in marriage. Alchemical commentators before Maier, notably Robertus Vallensis in De Veritate Artis Chemicae and Jodocus Greverus in Secretum Nobilissimorum, had already read this myth as an allegory of the volatile-fixed dynamic central to the Great Work. De Jong demonstrates that Maier elevates Atalanta from an illustrative example to the organizing principle of his entire emblem book, making her flight the master metaphor for volatile Mercury that cannot be captured by brute force but only through the cunning application of Art. In the frontispiece, the three-voice fugal structure assigns Atalanta the fleeing voice that the pursuing Hippomenes (Sulphur) can only overtake with the aid of the golden apples (the catalytic agent). De Jong shows that this allegorical logic structures all fifty emblems, each of which dramatizes some aspect of the pursuit, capture, and union of the volatile and fixed principles."
    ),
    (
        "aurora-consurgens",
        "The Aurora Consurgens is a late medieval alchemical text attributed to Pseudo-Aquinas, remarkable for its systematic fusion of Solomonic wisdom literature with alchemical symbolism through a Christological interpretive framework. The text reads the biblical personification of Wisdom as a figure for the transformative agent of the Great Work, thereby grounding alchemy in sacred scripture and patristic authority. De Jong identifies the Aurora Consurgens as a source that Maier accesses indirectly through the Rosarium Philosophorum, which transmits its sapiential-Christological reading into the dense scriptural marginalia of Emblems XXVI and XXVII. In these emblems, Maier presents Wisdom as the tree of life and defines alchemy as knowledge joined with practice, a formulation that draws on the Aurora's equation of divine sapientia with alchemical scientia. The text represents the religious-philosophical dimension of the alchemical tradition that Maier deliberately foregrounds, positioning the Great Work as a form of sacred knowledge rather than mere laboratory technique."
    ),
    (
        "aurum-philosophicum",
        "Philosophical gold is a foundational distinction in the alchemical tradition, separating the common gold found in nature from the perfected substance produced by the art of the philosopher, which embodies the solar principle in its highest possible form. The Rosarium Philosophorum insists on this distinction, teaching that the gold sown by the alchemist is not metallic bullion but a seed-principle capable of generating further perfection when planted in properly prepared matter. De Jong traces Maier's use of this concept to Emblem VI, where gold must be sown in white foliated earth to yield an abundant harvest, an agricultural metaphor that makes philosophical gold analogous to a living seed rather than an inert metal. Maier consistently warns against confusing the two kinds of gold throughout his discourse, following a long tradition in which the vulgar understanding of alchemy as mere gold-making is rejected in favor of a philosophical understanding of transmutation as the perfection of matter. In De Circulo Physico Quadrato, Maier further develops the connection between philosophical gold, the human heart, and the sun as three manifestations of the same central principle operating in different registers of creation."
    ),
    (
        "calcination",
        "Calcination, the reduction of a substance to ash through sustained heating, was understood in the alchemical tradition as one of the fundamental purgative operations that strip matter of its volatile and impure components, leaving behind a stable residue ready for further work. Ancient metallurgists recognized that heating metals to extreme temperatures could separate out dross and reduce them to their calx or oxide, and alchemists generalized this observation into a principle of purification through fire. De Jong shows that Maier subsumes calcination within the broader washing and bleaching metaphor of Emblem III, where the laundress's work represents all purificatory operations including burning away impurities, rather than treating it as an isolated step. This is characteristic of Maier's approach throughout Atalanta Fugiens: individual operations are absorbed into symbolic clusters that operate simultaneously across chemical, medical, and spiritual registers. The Turba Philosophorum's teaching that the soul is withdrawn through putrefaction and calcination until nothing remains provides the doctrinal basis for Maier's treatment of fire as both destroyer and purifier."
    ),
    (
        "catena-aurea",
        "The Catena Aurea or Golden Chain is a concept with deep roots in Neoplatonic philosophy, where it designates the unbroken continuum linking the divine to the material world, ensuring that every level of being participates in and reflects the one above it. Alchemists adopted the image to express their conviction that transmutation in the laboratory mirrors and participates in cosmic processes of transformation, from base matter up through the celestial spheres to the divine source. De Jong reads Maier's invocation of the Golden Chain in Emblem V as an expression of the Hermetic principle articulated in the Tabula Smaragdina: that which is below is like that which is above, to accomplish the miracles of one thing. For Maier, each stage of the alchemical Work corresponds to a celestial operation, so that the purification of matter in the vessel recapitulates the purification of the soul in the cosmos. This macrocosm-microcosm correspondence, elaborated at length in De Circulo Physico Quadrato, provides the metaphysical foundation for Maier's entire emblem program."
    ),
    (
        "cauda-pavonis",
        "The Cauda Pavonis or Peacock's Tail refers to the iridescent display of shifting colors that alchemists reported observing in the vessel during the transitional phase between the nigredo and the albedo, when the blackened matter begins to break down and reorganize. This phenomenon was widely discussed in alchemical literature as a sign that the putrefaction was complete and the matter was beginning its ascent toward whiteness, with the full spectrum of colors interpreted as evidence that all the elements were in active interplay. De Jong notes that Maier alludes to color transformations across the emblem sequence, using them as markers of progress through the stages of the opus: black for Saturn and putrefaction, the peacock's iridescence for the transition, white for purification, and red for completion. The Rosarium Philosophorum describes the sequence from blackness through the colors to whiteness in terms that inform Maier's visual program. For Maier, the Peacock's Tail represents the moment of maximum instability and promise, when the old form has been destroyed but the new one has not yet stabilized."
    ),
    (
        "ceres",
        "Ceres, the Roman goddess of grain, harvest, and maternal nourishment, was adopted by alchemists as a figure for the fertile, receptive earth principle that sustains the growing seed of the philosophical work through its long period of maturation. In the classical mystery tradition, Ceres' search for her daughter Proserpina and the seasonal cycle of growth, death, and renewal provided a ready-made mythological framework for the alchemical process of dissolution, burial, and regeneration. De Jong reads Maier's agricultural goddesses in Atalanta Fugiens as figures for the receptive, nourishing matter that sustains the seed of gold toward its maturation, connecting Ceres to the nursing and nourishment imagery of the opening emblems. Maier's equation of earth-goddesses with alchemical matter follows a tradition reaching back to the Hellenistic period, when alchemists first associated Isis, Demeter, and Ceres with the material substrate of the Work. In Atalanta Fugiens, the earth-as-nurse who feeds the philosophical child provides the counterpart to the solar father principle, establishing the gendered complementarity that structures the entire emblem sequence."
    ),
    (
        "circulatio",
        "Circulatio or circular distillation is the operation in which the volatile component of a substance is repeatedly raised by heat, condensed, and returned to the matter below, each cycle refining the product further until perfection is achieved. The operation was performed in specialized vessels such as the pelican, where the distillate flows back onto the original material in a continuous loop. De Jong reads the circular imagery of Emblem XXI, where the geometric progression from circle to square to triangle and back to circle encodes the entire alchemical process, as Maier's master figure for the iterative nature of the Work. The Rosarium Philosophorum, the source of Emblem XXI's motto, teaches that the philosopher must repeatedly cycle through the stages of dissolution and coagulation, with each pass bringing the matter closer to the unchangeable redness of the completed Stone. Maier's insistence on circularity reflects a fundamental alchemical principle: the Work begins and ends in unity, and the path from prima materia to lapis philosophorum is not linear but cyclical."
    ),
    (
        "citrinitas",
        "Citrinitas, the yellowing, is the transitional stage of the alchemical process that falls between the albedo (whitening) and the rubedo (reddening), representing the moment when purified white matter begins to receive the vivifying warmth that will bring it to perfection. In the classical four-stage color sequence of nigredo, albedo, citrinitas, and rubedo, the yellowing was associated with the element of air and the quality of the soul, as distinct from the body (earth/black) and the spirit (water/white). De Jong notes that Maier treats citrinitas as a transitional moment rather than a fully dramatized stage in Atalanta Fugiens, with no single emblem devoted exclusively to it. Tilton reads the yellowing into the geometric progression of Emblem XXI, where the soul-as-air phase in the triangle corresponds to the intermediate vivification between albedo and rubedo. The relative silence around citrinitas in Atalanta Fugiens reflects a broader trend in post-medieval alchemy, where many authors collapsed the four-stage model into three, absorbing the yellowing into the transition from white to red."
    ),
    (
        "coagulation",
        "Coagulation is the operation of solidifying the volatile, rendering fluid mercurial matter into a stable, fixed form through the application of controlled heat or the action of a complementary principle. In the Turba Philosophorum's foundational teaching, coagulation and dissolution are inseparable complementary operations: one nature coagulates only through the dissolution of another, a principle expressed in the Latin formula 'Coagulatio unius naturae non fit absque dissolutione alterius.' De Jong traces Maier's illustration of this concept to Emblem V, where the toad grows large from the woman's milk as the fixed principle solidifies through the dissolution of the volatile, and the woman dies as the toad coagulates. The Pseudo-Aristotelian Tractatulus de Practica Lapidis and the Lullian tradition both contribute to Maier's understanding of coagulation as a reciprocal process rather than a unilateral imposition of form on matter. In the Scale Philosophorum's formula 'solve et coagula,' which Maier uses as a source text, coagulation represents the constructive half of the fundamental binary rhythm that drives the entire Work."
    ),
    (
        "coniunctio",
        "The coniunctio oppositorum or union of opposites is the central operation of the alchemical Great Work, in which male and female, fixed and volatile, Sun and Moon, sulphur and mercury are brought together in a generative marriage that produces the Philosopher's Stone. De Jong identifies this theme across fourteen emblems in Atalanta Fugiens, making it the structural backbone of the entire sequence, appearing in forms as diverse as the brother-sister marriage of Emblem IV, the Sol-Luna union in Emblem XXX, and the hermaphrodite figures of Emblems XXXIII, XXXIV, and XXXVIII. The Rosarium Philosophorum, Maier's primary source for the coniunctio imagery, depicts the union as a series of stages progressing from courtship through coitus to death and resurrection, a narrative sequence that Maier distributes across his emblem program. Senior Zadith's Tabula Chimica provides the complementary image of Luna addressing Sol: 'You need me like the Cock the Hen, and I need your action.' Maier's formulation in Symbola Aureae Mensae crystallizes the principle: 'Create equality among the elements and you will have completed the Work.'"
    ),
    (
        "de-lapide-philosophico",
        "The De Lapide Philosophico is an alchemical emblem book attributed to Lambsprinck, pairing symbolic engravings of natural and mythological scenes with verse explanations that encode the stages of the Great Work in visual form. Published in the Musaeum Hermeticum compilation, it represents one of the most important precedents for the genre of the alchemical emblem book that Maier would bring to its fullest expression in Atalanta Fugiens. De Jong and Pagel both identify Lambsprinck's work as a prototype for Maier's method of encoding alchemical doctrine in pictorial form, noting that Emblem VII's imagery of winged and wingless birds draws on a shared symbolic vocabulary. The pairing of a volatile, ascending figure with a fixed, earthbound counterpart that must be united appears in both Lambsprinck and Maier, reflecting the widespread use of bird symbolism in the Mercury-Sulphur tradition. Lambsprinck's influence extends beyond individual motifs to the structural principle that a carefully ordered sequence of images can serve as a complete guide to the alchemical process."
    ),
    (
        "de-veritate-artis-chemicae",
        "The De Veritate et Antiquitate Artis Chemicae is a sixteenth-century treatise by Robertus Vallensis that defends the great antiquity and legitimacy of alchemy by demonstrating that classical myths contain encoded alchemical teachings, including a reading of the Atalanta-Hippomenes footrace as an allegory of the volatile-fixed dynamic. De Jong identifies Vallensis as a direct source for Maier's frontispiece commentary, where the race between Atalanta and Hippomenes is systematically interpreted as the pursuit of volatile Mercury by fixed Sulphur, with the golden apples serving as the catalytic agent of Art. Vallensis thus provides the hermeneutic precedent for the central allegorical conceit that gives Atalanta Fugiens its title and organizing principle. The treatise belongs to a tradition of defenses of alchemy that stretches from Petrus Bonus's Margarita Pretiosa Novella in the fourteenth century through the sixteenth-century revival of mythological-alchemical interpretation. Maier's debt to Vallensis illustrates a characteristic feature of his scholarly method: grounding his most original claims in the authority of earlier commentators."
    ),
    (
        "dissolution",
        "Dissolution, the breaking down of solid form into liquid, is one of the two fundamental operations of the alchemical art, paired with coagulation in the master formula solve et coagula. The Turba Philosophorum teaches that all creation begins in liquefaction and that the Work cannot proceed until the existing form has been completely destroyed and returned to the undifferentiated state of prima materia. De Jong traces dissolution imagery throughout Atalanta Fugiens, from the woman's death as the toad feeds in Emblem V to the mutual annihilation of dragon and woman in Emblem L, which provides the culminating image of the entire emblem sequence. Maier frames dissolution as simultaneously destructive and generative: every death of form is also a liberation of the matter's hidden potential, a principle he dramatizes through the recurring death-and-resurrection narratives of Adonis, Osiris, and King Duenech. De Jong reads Emblem L's return to primary matter as the final dissolution that both completes and restarts the Work, reflecting the circular logic that governs the alchemical process from beginning to end."
    ),
    (
        "distillatio",
        "Distillation is the operation of separating a substance into its volatile and gross components by heating it until the volatile portion rises as vapor, then condensing and collecting the purified distillate. In practical alchemy, distillation was performed using retorts, alembics, and pelican vessels, and could be repeated multiple times to achieve progressively greater purity. De Jong connects Maier's distillation imagery to the practical apparatus referenced in Emblem II, where the retort serves as both a laboratory instrument and a symbolic womb in which the volatile spirit is separated from dense matter and recollected in purified form. In Emblem XXX's summary of operations, Maier lists distillatio alongside solutio, coagulatio, sublimatio, and fixatio as the essential stages that can all be comprised under the single word 'cooking.' De Jong shows that for Maier, as for the tradition he inherits, distillation is never a purely mechanical operation but always carries symbolic overtones of purification, refinement, and the separation of the subtle from the gross as taught in the Tabula Smaragdina."
    ),
    (
        "divinae-institutiones",
        "The Divinae Institutiones is a patristic work by Lactantius, the early fourth-century Christian apologist, which argues that divine wisdom is the true nourishment of the soul and that pagan philosophy contains scattered fragments of a primordial revelation. De Jong identifies Lactantius as one of the sources feeding into the dense scriptural apparatus of Emblem XXVI, where Maier assembles an unusually large number of biblical and patristic references to establish the sapiential foundations of the alchemical enterprise. The concept of wisdom as food of the soul, drawn from the Solomonic tradition and reinforced by Lactantius's Christian authority, bridges theology and alchemical practice in Maier's presentation. This patristic strand reinforces Maier's broader argument that alchemy is a form of sacred knowledge with roots predating Greek philosophy, a claim that De Jong traces through the chain of authorities from Hermes Trismegistus through the Arabic-Latin transmission to the Renaissance compilations. The inclusion of Lactantius alongside Hermetic and biblical sources demonstrates Maier's characteristic method of legitimating alchemy by embedding it within the broadest possible tradition of divine wisdom."
    ),
    (
        "dragon",
        "The dragon is one of the most ancient and versatile symbols in alchemical iconography, appearing as the guardian of treasure, the ouroboric figure of self-consuming transformation, and the volatile spirit that must be slain and reconstituted before the Work can be completed. In Hellenistic alchemy, the serpent or dragon biting its own tail (ouroboros) represented the cyclical unity of the alchemical process, where the end feeds back into the beginning. De Jong traces Maier's dragon imagery in Emblem L to the Turba Philosophorum's teaching on the reciprocal annihilation of contraries, where the dragon and woman destroy each other in a mutual dissolution that returns all to primary matter. This final emblem of Atalanta Fugiens provides the culminating image of the entire Work: the volatile principle (dragon) and the nourishing feminine principle (woman) consume each other, and from their mutual destruction the possibility of the perfected Stone emerges. De Jong reads the dragon as Maier's figure for the volatile, corrosive spirit that is both the most dangerous obstacle and the most essential ingredient in the Great Work."
    ),
    (
        "elixir",
        "The Elixir is the perfected alchemical medicine capable of healing all disease in the human body and transmuting base metals into gold, making it synonymous with the Philosopher's Stone in its active, therapeutic aspect. The concept entered Western alchemy from the Arabic tradition, where al-iksir designated a dry powder of transmutation, and over centuries it acquired an increasingly medical significance as alchemists claimed their art could produce a universal remedy. De Jong and Pagel both emphasize the medical dimension of Atalanta Fugiens, where the curative potion administered to King Duenech in Emblem XLVIII encodes the Elixir as the perfected product of the Work applied to the sick body. Maier's training as a physician is evident in his treatment of the Elixir, which bridges metallurgical transmutation and therapeutic practice within a single symbolic framework. The Merlini allegory provides the narrative structure: the king's disease requires a medicine that can only be prepared through the complete cycle of dissolution, purification, and reconstitution, making the Elixir both the goal and the proof of the alchemist's mastery."
    ),
    (
        "fama-fraternitatis",
        "The Fama Fraternitatis, published anonymously in 1614, is the first of the three Rosicrucian manifestos that announced the existence of the Brotherhood of the Rose Cross and called for a universal reformation of knowledge through the integration of natural philosophy, medicine, and spiritual illumination. The manifestos created an intellectual sensation across Europe, and Tilton argues that Maier's Atalanta Fugiens, published just three years later in 1617, responds directly to the Rosicrucian moment the Fama inaugurated. While no emblem motto derives directly from the Fama, the manifesto provides the ideological context within which Maier's unprecedented synthesis of music, image, and alchemical text becomes intelligible as a contribution to the universal reformation of learning. Tilton documents Maier's active attempts to contact the Brotherhood, suggesting that Atalanta Fugiens may itself serve as a public demonstration of the kind of integrated knowledge the Rosicrucians advocated. The Fama thus represents not a textual source in the manner of the Turba or Rosarium, but the contemporary intellectual horizon against which Maier's most ambitious work must be understood."
    ),
    (
        "fermentatio",
        "Fermentation in the alchemical tradition is the penultimate operation that introduces a vivifying agent, the ferment, into the nearly completed substance to bring it to its final state of activity and potency. The analogy with bread-making, where a small quantity of leaven transforms the entire mass of dough, was widely used by alchemists to explain how a tiny quantity of the perfected Stone could transmute a vastly larger quantity of base metal. De Jong connects Maier's treatment of fermentation to the agricultural metaphors of Emblem VI, where the ferment of gold activates the receptive white earth to produce the final multiplication, and where the sowing metaphor implies that the ferment is a living seed rather than an inert additive. The Rosarium Philosophorum describes fermentation as the stage at which the previously inert product acquires its transmutative power, a teaching Maier incorporates into his sequential model of the Work. For Maier, fermentation marks the transition from passive preparation to active potency, the moment when the completed substance begins to act upon the world."
    ),
    (
        "fixatio",
        "Fixation is the operation of rendering the volatile mercurial spirit permanent, stable, and resistant to fire, transforming what flees from the vessel into what remains steadfast within it. The concept is fundamental to the Mercury-Sulphur theory that dominates the alchemical tradition from Jabir ibn Hayyan onward, where the volatile mercury principle must be fixed by the stable sulphur principle before the perfected metal can be achieved. De Jong identifies the pursuit-and-capture motif of the frontispiece as Maier's master allegory for fixation: Hippomenes must capture and fix the fleeing Atalanta, and he can only do so through the golden apples of Art rather than through brute force. This reading makes fixation not merely one operation among many but the governing metaphor of the entire emblem book, since every emblem dramatizes some aspect of the volatile-fixed dynamic. De Jong demonstrates that the wingless figures in Emblems VII and XVI represent the fixed sulphur principle, while their winged counterparts represent the volatile mercury that must be captured and rendered permanent."
    ),
    (
        "fugue",
        "The three-voice fugal canons accompanying each of the fifty emblems in Atalanta Fugiens represent Maier's most original contribution to the emblem tradition, creating an unprecedented synthesis of music, image, and text that has no parallel in earlier or later alchemical literature. Each fugue assigns its three voices allegorical identities: the fleeing voice represents Atalanta (volatile Mercury), the pursuing voice represents Hippomenes (fixed Sulphur), and the resolving voice represents the Golden Apple (the catalytic agent that enables their union). Wescott and Leedy have both analyzed the musical structure, demonstrating that the contrapuntal relationships between the voices encode the alchemical dynamics of pursuit, resistance, and eventual harmonization. De Jong situates the fugues within Maier's broader understanding of cosmic harmony, where the proportional relationships governing musical intervals mirror the proportional relationships governing the combination of elements in the Great Work. The choice of the fugue form, with its built-in structure of flight and pursuit, makes the musical setting not merely an ornament but an integral expression of the book's central allegorical argument."
    ),
    (
        "hermaphrodite",
        "The Hermaphrodite is the alchemical figure of the two-in-one, the embodied result of the coniunctio oppositorum in which male and female principles achieve stable union within a single body. Maier devotes three emblems to this figure: Emblem XXXIII shows a darkened Hermaphrodite resembling a dead person who requires fire to complete its transformation, Emblem XXXIV depicts the Hermaphrodite as a united being of complementary natures, and Emblem XXXVIII identifies it with the Rebis or 'two-thing' born from the mountains of Mercury and Venus. De Jong reads the darkened Hermaphrodite of Emblem XXXIII through the Turba Philosophorum's teaching that when all four qualities are present simultaneously, the result is a Hermaphroditic being, and that the transformation of this being into its final form requires the removal of moisture and the application of fire. The Rosarium Philosophorum provides the iconographic source, where the death and resurrection of the conjoined king and queen culminate in the Hermaphrodite as a figure of perfected unity. Miner connects Maier's Hermaphrodite images to a broader iconographic tradition that extends through the seventeenth century to William Blake."
    ),
    (
        "hippomenes",
        "In Ovid's telling, Hippomenes is the suitor who defeats Atalanta in the footrace by rolling three golden apples given to him by Venus across her path, each apple distracting the maiden long enough for him to gain ground. De Jong reads Hippomenes as Maier's figure for the alchemical adept who must apply the disciplined techniques of Art to slow and capture the volatile mercurial principle, since brute pursuit of Mercury without the catalytic golden apples would be futile. The identification of Hippomenes with fixed Sulphur follows from the frontispiece's allegorical program, where the fleeing Atalanta represents volatile Mercury and the pursuing youth represents the solar, masculine, fixed principle. De Jong traces this reading through the chain of alchemical commentators from Robertus Vallensis to Jodocus Greverus, who established the precedent for interpreting the Ovidian myth as a technical allegory of the volatile-fixed dynamic. In the three-voice fugal structure, Hippomenes takes the pursuing voice, always following and responding to Atalanta's flight, embodying the patient persistence that the alchemical tradition demands of the practitioner."
    ),
    (
        "isis",
        "Isis, the Egyptian goddess who searched for and reassembled the dismembered body of her husband Osiris after his murder by Typhon, was one of the earliest mythological figures adopted by the alchemical tradition as a symbol of the restorative, lunar principle that gathers and reconstitutes what has been dissolved and scattered. Greek alchemical writers explicitly connected Isis with the feminine, mercurial agent of the Work, and this identification persisted through the Arabic and Latin transmission. De Jong shows that Maier presents Isis in Emblem XLIV as the feminine restorative principle who collects the scattered parts of the slain Osiris, encoding the reintegration phase that follows the necessary destruction of the nigredo. Within the broader pattern of Atalanta Fugiens, Isis belongs to a series of female figures including Venus, Latona, and the Queen who preserve and reconstitute what the masculine principle alone cannot. De Jong reads the Isis-Osiris cycle alongside the Adonis-Venus and King Duenech narratives as parallel expressions of the same alchemical truth: that restoration requires a feminine, lunar agent to complement the solar principle destroyed in the dissolution."
    ),
    (
        "king-duenech",
        "King Duenech is the central figure of the Merlini allegory and the wider tradition of the suffering alchemical king, appearing in Atalanta Fugiens in Emblems XXVIII and XLVIII as a monarch afflicted with melancholic disease whose cure encodes the entire alchemical process in medical terms. De Jong's 1964 article in the Netherlands Yearbook for History of Art first established the textual genealogy of this figure, tracing the king's illness, steam-bath purification, and eventual restoration to the Allegoria Merlini as transmitted through the Artis Auriferae. Pagel emphasizes the three-level physiological correspondence in Maier's treatment: the king's disease (black bile, dropsy) maps onto the impurity of base metal and the corruption of the fallen soul, and his cure through graduated applications of heat mirrors the alchemical coction that proceeds from nigredo through albedo to rubedo. De Jong and Wescott both identify a four-emblem King cycle (Emblems XXIV, XXVIII, XXXI, and XLVIII) that dramatizes the sickness, death, rescue, and resurrection of the solar principle. Maier's training as a physician gives the King Duenech narrative a clinical specificity unusual in the emblem tradition, with the king's symptoms and treatments described in terms drawn from contemporary medical practice."
    ),
    (
        "lapis",
        "Lapis, shorthand for Lapis Philosophorum, designates the perfected product of the Great Work in alchemical literature, a substance credited with the power to transmute base metals into gold, heal all diseases, and achieve spiritual perfection in the practitioner. The concept has roots reaching back to the earliest Arabic alchemical texts, where the Stone was identified with the elixir al-iksir, and it acquired increasingly elaborate symbolic associations as it passed through the Latin transmission. De Jong identifies the Stone as the telos toward which the entire fifty-emblem sequence of Atalanta Fugiens converges, with the geometric formula of Emblem XXI encoding its method of production: the progression from circle (unity) through square (four elements) and triangle (tria prima) back to circle (perfected unity). According to Morienus, as Maier quotes in the Viatorium, Adam took the Philosopher's Stone with him from Paradise, and since that time it has been present in every person, a teaching that grounds the alchemical quest in the condition of human existence itself. De Jong argues that for Maier the Stone is the image of the perfected union of all opposites, achieved only after the complete cycle of dissolution, purification, and reconstitution."
    ),
    (
        "latona",
        "Latona (Leto in Greek mythology) is the mother of Apollo and Diana, identified in the alchemical tradition with the impure base metal laton or latten that must be whitened and purified before it can give birth to the solar and lunar principles of the Work. De Jong connects the name Latona to the alchemical term laton through a wordplay that was standard in the tradition, making the goddess a mythological personification of the material substrate in its unworked, impure state. In Emblem VI, Maier uses Latona as a figure for the impure matter that must be washed and whitened before gold can be sown in it, following the Rosarium Philosophorum's teaching about sowing gold in white foliated earth. De Jong reads the planetary mythology further: Saturn produces Jupiter, who produces the hazy whiteness, and Jupiter begets Diana (perfect whiteness) and Apollo (perfect redness) with Latona, encoding the entire color sequence of the opus in a genealogical narrative. The presence of Latona at the birth of Sol and Luna in Emblem XI reinforces her role as the maternal, material ground from which the purified principles emerge."
    ),
    (
        "liber-sapientiae",
        "The Liber Sapientiae or Book of Wisdom, attributed to Solomon in the biblical tradition, is a sapiential text that personifies Wisdom as a divine creative agent present at the origin of the world and accessible to those who seek her with purity of heart. Alchemists in the medieval and Renaissance periods systematically appropriated the Solomonic wisdom tradition to legitimate their art as a form of sacred knowledge, identifying the Wisdom who orders all things with the transformative principle that governs the Great Work. De Jong demonstrates that Maier draws on this tradition in Emblems XXVI and XXVII, where the unusually dense scriptural marginalia signal that the sapiential framework is being deliberately foregrounded. The Rosarium Philosophorum and the Aurora Consurgens serve as the mediating texts through which Maier accesses the biblical identification of Wisdom with the tree of life, a figure he applies to the alchemical art as the root of all knowledge and practice. Maier's definition of alchemy in Emblem XXVI as 'cognitionem chymiae cum praxi,' knowledge joined with practice, crystallizes the sapiential ideal that true wisdom is inseparable from its embodiment in the Work."
    ),
    (
        "luna",
        "Luna, silver, and the Moon constitute the feminine, receptive, cold, and moist pole of the alchemical binary that structures the entire tradition from Jabir ibn Hayyan onward, paired always with Sol, gold, and the Sun as the masculine, active, hot, and dry counterpart. De Jong traces Maier's lunar symbolism to the Senior Zadith tradition, particularly the Tabula Chimica's 'Letter of the Sun to the Waxing Moon,' where Luna declares her need for Sol's warmth and Sol acknowledges his need for Luna's capacity for multiplication. In Atalanta Fugiens, the lunar principle is figured through the fleeing Atalanta of the frontispiece, the winged bird figures of Emblems VII and XVI, and the feminine partners in the marriage and coniunctio emblems. De Jong demonstrates that Maier follows the Rosarium's teaching that Sol has no value without Luna and Luna without Sol, since only their union produces the tinctura. The lunar principle's association with Mercury, volatility, and the receptive feminine makes it the mobile, elusive counterpart that the fixed solar principle must pursue and capture throughout the emblem sequence."
    ),
    (
        "mercurius",
        "Mercurius Philosophorum, the philosophical Mercury, is the most polyvalent and central concept in the alchemical tradition, signifying simultaneously the liquid metal mercury, the volatile feminine principle, the primordial water from which creation arose, the water of death in which metals decompose, and the water of resurrection from which they rise again as gold. De Jong traces this polyvalence to Greek alchemical writings, where Zosimos describes mercury as 'the divine and great mystery, the object one is looking for, the Universe itself,' and identifies it as both the beginning and the end of the Work. In Atalanta Fugiens, Mercury appears most explicitly in the frontispiece as Atalanta, the fleeing volatile principle that Hippomenes (Sulphur) must pursue, and in the winged figures of Emblems VII and XVI that consistently signify the mercurial principle in its lunar, feminine aspect. De Jong shows that Maier inherited the Jabir ibn Hayyan tradition in which sulphur and mercury are the two component principles from which all metals are formed, with their varying proportions accounting for the differences between metals. Later alchemists extended Mercury's significance to include the winged messenger of the gods, mediator between heaven and earth, and the hermaphroditic being that contains all opposites within itself."
    ),
    (
        "metamorphoses",
        "Ovid's Metamorphoses, the sprawling Latin epic poem composed around 8 CE, narrates over two hundred mythological transformations and provides the direct literary source for the titular narrative of Atalanta Fugiens. Maier draws the footrace between Atalanta and Hippomenes from Metamorphoses X.560-704, reading Ovid's tale of the maiden who is finally outrun through Venus's golden apples as an allegory of the volatile-fixed dynamic at the heart of the alchemical process. De Jong demonstrates that this Ovidian source is not received directly but mediated through the alchemical commentators Robertus Vallensis and Jodocus Greverus, who had already established the precedent for reading Ovid's myths as encoded alchemical teachings. The broader tradition of reading the Metamorphoses as a repository of alchemical wisdom reaches back to Petrus Bonus in the fourteenth century, who claimed that Homer, Virgil, and Ovid were among those who transmitted hermetic wisdom. Maier extends this tradition more systematically than any predecessor, devoting multiple emblems to mythological narratives drawn from or inspired by Ovid's transformations."
    ),
    (
        "mortificatio",
        "Mortificatio, the killing or death of the old form, is the operation through which existing structure is destroyed as a necessary prerequisite for the emergence of new and more perfect forms, closely associated with both putrefaction and the nigredo stage. The alchemical tradition consistently teaches that no transformation is possible without the prior death of what exists, a principle that Maier illustrates through the death of the woman in Emblem V, the killing of Osiris in Emblem XLIV, and the mutual destruction of dragon and woman in Emblem L. De Jong reads these death scenes as encoding the alchemical axiom that bodies cannot be changed without putrefaction, citing the Rosarium Philosophorum's explicit comparison with Christ's testimony about the grain of wheat that must fall into the earth and die before it can bear fruit. The mortificatio is represented iconographically by the black crow in Emblem XLIII, where clipped wings signify that the volatile spirit has been subdued. De Jong shows that Maier treats mortificatio not as an isolated stage but as a recurring necessity, since each level of the Work requires its own death before the next can begin."
    ),
    (
        "multiplicatio",
        "Multiplication is the final augmentation of the Philosopher's Stone's transmutative power, the operation through which the perfected product is increased in both quantity and potency so that it can transform quantities of base metal far exceeding its own mass. The concept draws on agricultural metaphors that pervade the alchemical tradition: just as a single seed produces many seeds, the completed Stone can be 'sown' to generate further instances of itself. De Jong reads Maier's treatment of multiplication through the agricultural imagery of Emblem VI, where sowing gold in white foliated earth yields an abundant harvest, and where the metaphor implies that the Stone is a living, self-propagating agent rather than an inert substance. The Rosarium Philosophorum describes multiplication as the final stage of the Work, following fermentation, in which the Stone's power is repeatedly doubled through further cycles of dissolution and coagulation. For Maier, multiplication represents the ultimate vindication of the alchemical art: the proof that nature, perfected by art, can transcend the limitations of ordinary material processes."
    ),
    (
        "nigredo",
        "The nigredo or blackening is the first and most dreadful stage of the alchemical Work, in which the matter in the vessel undergoes complete decomposition, putrefaction, and the death of its existing form, visually signaled by the appearance of a deep black color. In the tradition transmitted through the Rosarium Philosophorum, the nigredo is associated with Saturn, the planet of coldness, inertia, and melancholy, whose leaden darkness must be overcome before any progress toward whiteness is possible. De Jong identifies the nigredo in Maier's depictions of death, putrefaction, and burial, particularly in Emblem XXVIII where King Duenech suffers from black bile, and Emblem XLIII where black crows represent the putrefaction stage. The Turba Philosophorum teaches that beneath the blackness the true whiteness is hidden, and De Jong shows that Maier dramatizes this principle across the emblem sequence: the darkened hermaphrodite of Emblem XXXIII signals the necessary dissolution before renewal. The simultaneous dread and necessity of the nigredo reflects a core alchemical conviction: the most complete destruction is the prerequisite for the most perfect creation."
    ),
    (
        "oedipus",
        "Oedipus, the solver of the Sphinx's riddle in Greek mythology, was adopted by the alchemical tradition as a figure for the adept who must decode the deliberately obscure symbolic language in which the secrets of the Art are concealed. Maier presents Oedipus in Emblem XXXIX as the intellectual hero who penetrates the veil of riddle and allegory that guards alchemical knowledge from the unworthy. De Jong reads this as Maier's self-conscious commentary on the hermeneutic challenge posed by the entire alchemical literary tradition, where the truth is intentionally wrapped in mythological narratives, paradoxical formulations, and symbolic images that require intellectual penetration. The Sphinx, as guardian of secrets, represents the deliberate obscurity that alchemical authors cultivated to protect their teachings from misuse, a practice Maier both inherits and perpetuates in the elaborate multi-layered structure of Atalanta Fugiens itself. De Jong connects the Oedipus-Sphinx motif to Maier's broader theme that the Work requires not only manual skill but philosophical understanding, making the solving of riddles an integral part of the alchemical process rather than merely a literary ornament."
    ),
    (
        "opus-magnum",
        "The Opus Magnum or Great Work is the comprehensive term for the entire alchemical project of transmuting base matter into the perfected Philosopher's Stone, encompassing all the individual operations from initial dissolution through the color stages to final projection. In the tradition Maier inherits, the Great Work is understood not merely as a sequence of laboratory procedures but as a cosmic process that recapitulates the creation and perfection of the world in miniature within the sealed vessel. De Jong argues that Maier conceives Atalanta Fugiens itself as a symbolic enactment of the Opus Magnum, with the deliberate ordering of the fifty emblems reflecting the sequential logic of the Work from the cosmological foundations established in Emblems I and II through purification, conjunction, and final perfection. The frontispiece's allegorical program of pursuit and capture provides the narrative framework, while the geometric formula of Emblem XXI provides the philosophical summary: the progression from circle to square to triangle and back to circle encodes the entire Great Work in a single figure. Maier's treatment reflects the Renaissance conviction that to describe the Work truly is, in some sense, to perform it."
    ),
    (
        "osiris",
        "Osiris, the Egyptian god murdered by his brother Typhon, dismembered, and reassembled by his wife Isis, was among the earliest mythological figures to be read as an alchemical allegory, with Greek-Hellenistic alchemists already identifying his death and resurrection with the dissolution and reconstitution of matter in the Great Work. De Jong demonstrates that Maier follows this ancient interpretive tradition in Emblem XLIV, where the killing of Osiris by Typhon encodes the destruction of the solar principle by the corrosive agent of dissolution, and Isis's gathering of the scattered limbs represents the reintegration that follows the nigredo. Maier explicitly equates Osiris with Adonis, Dionysus, and Sol as interchangeable names for the Philosophical Sun that must die and be reborn. The annual Egyptian mourning for Osiris, followed by celebrations of his resurrection, provides Maier with a cultural parallel to the alchemical sequence of nigredo, albedo, and rubedo. De Jong reads the Osiris-Typhon-Isis triad as Maier's most complete mythological expression of the three-part alchemical dynamic: the solar principle, the destructive agent, and the restorative feminine power."
    ),
    (
        "pelicanus",
        "The Pelican in alchemical usage refers both to a specialized circulatory vessel, in which the condensed distillate flows back down tubes into the body of liquid below for continuous redistillation, and to the Christological symbol of the bird that pierces its own breast to feed its young with its blood. De Jong connects both meanings in Maier's treatment, where the pelican vessel enables the circulatio essential to the Work while the self-sacrificing bird provides an image of matter that dissolves and reconstitutes itself through its own action. The identification of the pelican with Christ's sacrifice reinforced the alchemical tradition's claim that the Great Work parallels the redemptive process, with the Stone as a christological figure that dies and is reborn. De Jong reads the pelican symbolism in Atalanta Fugiens as part of the broader theme of circulatio, where the Work feeds upon itself in a self-sustaining cycle of dissolution and reconstitution. The dual practical-symbolic significance of the pelican exemplifies Maier's characteristic method of fusing laboratory apparatus with mythological and theological meaning."
    ),
    (
        "philosopher-s-stone",
        "The Philosopher's Stone or Lapis Philosophorum is the supreme goal of the alchemical Great Work, a substance or state of perfection credited with the power to transmute base metals into gold, cure all diseases as a universal medicine, and effect the spiritual perfection of the practitioner. The concept originates in the Arabic alchemical tradition and was transmitted to Western Europe through the Latin translations of the twelfth century, acquiring over centuries a vast accumulation of symbolic, theological, and philosophical associations. De Jong argues that Maier presents the Stone not through any single emblem but as the telos toward which the entire fifty-emblem sequence converges, with the geometric formula of Emblem XXI encoding the philosophical method of its production and the mutual destruction of Emblem L pointing to its achievement through the complete cycle of the Work. The Tabula Smaragdina's description of bringing together the forces of the cosmic soul into one solid matter provides the theoretical foundation, while the Rosarium's circle-square-triangle-circle formula provides the operational diagram. According to the legend Maier cites, Adam carried the Stone from Paradise, meaning that the capacity for perfection is inherent in human nature and requires only the art of the philosopher to actualize it."
    ),
    (
        "philosophical-egg",
        "The Philosophical Egg is the sealed vessel in which the prima materia undergoes its transformation, serving simultaneously as laboratory apparatus and cosmic symbol of the enclosed totality within which all differentiation and reunification occurs. De Jong interprets Maier's use of the egg in Emblem VIII as an image for the unity of all opposites before differentiation, a microcosm of the entire alchemical process contained in a single figure. The practical requirement of sealing the vessel hermetically to prevent the loss of volatile spirits during heating corresponds to the symbolic requirement that the Work must proceed within a self-contained system where nothing enters and nothing escapes. De Jong notes the perspective construction of Emblem VIII, where the philosophical egg in the foreground leads the eye through a series of architectural spaces to the innermost court where the alchemist will pierce it with a fiery sword, dramatizing the gradual penetration from the outer to the inner mystery. The egg imagery draws on ancient associations between the cosmic egg and the origin of the world, making the alchemist's sealed vessel a recreation of the primordial conditions from which all creation emerged."
    ),
    (
        "prima-materia",
        "Prima materia, the first matter or primary matter, is the undifferentiated starting material from which all metals and all created things arise, and to which they must be returned before the alchemist can reconstitute them in perfected form. The concept has roots in Aristotelian hylomorphism, where prime matter is pure potentiality without any form, and was adapted by alchemists to designate the chaotic, formless substrate that precedes all differentiation. De Jong shows that Maier treats prima materia as the hidden substrate underlying the entire emblem sequence, the formless potential that must be identified and worked upon before any transformation can begin, drawing on both the Aristotelian tradition and the Turba Philosophorum's teachings on primary matter. The fundamental alchemical insight that all manifestations emanate from one primary matter underwrites the possibility of transmutation itself: if all metals share a common origin, then returning them to that origin makes it possible to reconstitute them as gold. De Jong traces the recurring motif across Atalanta Fugiens where matter is dissolved, decomposed, and returned to its primary state as the prerequisite for every subsequent advance in the Work."
    ),
    (
        "projectio",
        "Projection is the final act of the Great Work, the moment when the perfected Philosopher's Stone is cast upon base metal to transmute it into gold, demonstrating that the entire preceding sequence of operations has achieved its goal. In the tradition transmitted through the Turba Philosophorum and the Rosarium, projection is described as the application of a minute quantity of the Stone to a vastly larger quantity of impure metal, with the Stone's transformative power propagating through the base substance like a ferment through dough. De Jong identifies projection as the implied telos toward which the entire pedagogical program of Atalanta Fugiens converges, the practical vindication that remains beyond the frame of the text itself. Maier's emblem sequence guides the reader through every stage of the Work up to and including the achievement of the Stone, but projection itself, the final test of success, remains implicit rather than depicted. This reticence reflects a widespread convention in alchemical literature, where the most closely guarded secret is not the preparation of the Stone but its application, the knowledge reserved for those who have earned it through completing the Work."
    ),
    (
        "putrefaction",
        "Putrefaction is the controlled decomposition of matter in the sealed vessel, the process through which the old form dies and returns to the chaotic state of prima materia, associated with the blackness of the nigredo and universally regarded as the indispensable gateway to all subsequent transformation. The Rosarium Philosophorum explicitly invokes Christ's parable of the grain of wheat that must fall into the earth and die before it bears fruit as the scriptural analogue to alchemical putrefaction. De Jong and Wescott both identify Maier's four-emblem King sequence (Emblems XXIV, XXVIII, XXXI, and XLIV) as an extended meditation on controlled decomposition, with King Duenech's suffering in Emblem XXVIII and Osiris's dismemberment in Emblem XLIV representing the necessary death of the old form. Maier represents putrefaction iconographically through black crows, burial imagery, and the chaos that appears when established forms break down, all drawn from the visual vocabulary of the Rosarium tradition. De Jong demonstrates that Maier understood putrefaction not as an isolated stage but as a necessary precondition operating at every level of the Work, from the initial dissolution of raw matter to the death that precedes the final resurrection of the perfected Stone."
    ),
    (
        "rebis",
        "The Rebis, from the Latin res bina meaning 'two-thing,' is the alchemical figure of the reunited opposites combined in a single substance, representing the successful product of the coniunctio that contains both masculine and feminine, fixed and volatile principles in stable union. De Jong identifies the Rebis with the Hermaphrodite in Maier's usage, noting that the epigram of Emblem XXXVIII makes the equation explicit, and that both figures are born from the two mountains of Mercury and Venus as described in the Turba Philosophorum. The Rebis appears in Atalanta Fugiens as an intermediate product rather than the final goal: it represents the state achieved after the union of opposites but before the additional operations of fermentation, multiplication, and projection that bring the Stone to its full potency. De Jong reads the Rebis through the Socrates passage in the Turba, where the Athenian philosopher is said to be known throughout the world through the fame of the Hermaphrodite, indicating the widespread recognition of the two-in-one principle. The distinction between the Rebis and the completed Lapis is significant for Maier's sequential model: the union of opposites is a necessary achievement but not yet the culmination of the Work."
    ),
    (
        "regina",
        "The Queen in alchemical allegory represents the lunar, feminine, volatile principle that complements the King's solar fixity, and their marriage constitutes the coniunctio that produces the Philosopher's Stone. In the Rosarium Philosophorum, the King and Queen are depicted in a progressive series of images moving from courtship through embrace, coitus, death, and resurrection as a unified Hermaphrodite, a visual narrative that Maier distributes across multiple emblems. De Jong reads the Queen as Maier's figure for the receptive mercurial principle, identifying her with Luna, silver, and the cold-moist temperament that must unite with the King's hot-dry nature. The Senior Zadith tradition provides the foundational image of Luna speaking to Sol: 'I need your action, for your nature is perfect, and I the waxing moon am cold and moist,' establishing the Queen's active desire for union as essential to the Work. De Jong demonstrates that the Queen's role in Atalanta Fugiens extends beyond passive receptivity, since Luna's capacity for multiplication is what Sol requires to become generative."
    ),
    (
        "rex",
        "The King in alchemical allegory represents Sol, gold, and the masculine fixed principle, and his narrative arc of sickness, death, and resurrection constitutes one of the most sustained symbolic sequences in the entire tradition. De Jong and Wescott identify a four-emblem King cycle in Atalanta Fugiens (Emblems XXIV, XXVIII, XXXI, and XLVIII) that dramatizes the complete alchemical process through the medical metaphor of a sovereign's affliction and cure. In Emblem XXIV the King rises from fire, in Emblem XXVIII King Duenech is purged of black bile in a steam bath, in Emblem XXXI the King calls for rescue from the sea of dissolution, and in Emblem XLVIII he is restored through the medicinal potion of the Merlini allegory. De Jong traces the King figure to the Rosarium Philosophorum's death-of-the-king sequence and the Allegoria Merlini, where the king 'tincta utraque' embodies both the suffering matter and the redemptive Christological parallel. Maier's King cycle encodes the entire Work in miniature: the solar principle must sicken (nigredo), be purified (albedo), and be restored to full power (rubedo) before the Stone can be achieved."
    ),
    (
        "rosarium-philosophorum",
        "The Rosarium Philosophorum or Rose Garden of Philosophers is one of the most influential compilations in the history of Western alchemy, a fourteenth-century anthology of extracts from earlier authorities organized around the stages of the Great Work, accompanied by a celebrated series of woodcut illustrations depicting the coniunctio of King and Queen. De Jong demonstrates that the Rosarium serves as Maier's single most important textual source after the Turba Philosophorum, providing the motto for Emblem XXI's geometric circle-square-triangle formula, the sapiential framework of Emblems XXVI and XXVII, and the iconographic program of the coniunctio sequence. The Rosarium also functions as the primary conduit through which Maier accesses the Aurora Consurgens, the Solomonic wisdom tradition, and the biblical-Christological dimension of the alchemical enterprise. De Jong reads the Rosarium's mediating role as crucial to understanding how Maier synthesizes disparate traditions into a unified emblematic program. The compilation's teaching that Sol has no value without Luna and that only their union produces the tinctura provides the doctrinal core around which Maier organizes the central emblems of Atalanta Fugiens."
    ),
    (
        "rubedo",
        "The rubedo or reddening is the final stage of the alchemical color sequence, signifying the achievement of perfection and the completion of the Philosopher's Stone, when the matter in the vessel attains the unchangeable red color of the tinctura rubea. In the tradition transmitted through the Turba Philosophorum, the red color is the highest indication of the quality and dignity of the Stone, surpassing all other properties as proof of its perfection. De Jong identifies the rubedo as structuring the entire second half of Maier's emblem sequence, with the color progression from black through white to red reaching completion in Emblem L. The geometric formula of Emblem XXI encodes the rubedo as the final return to the circle: after the square of the four elements and the triangle of the tria prima, the unchangeable redness signifies the achieved unity in which woman turns into man and they become one. De Jong connects the rubedo to the Rosarium's teaching that Venus's coloring of the white roses red with her blood in the Adonis myth encodes the transition from albedo to the final reddening, making the achievement of the Stone equivalent to the perfection of color itself."
    ),
    (
        "sapientia",
        "Sapientia, Wisdom personified, occupies a position of structural significance in Atalanta Fugiens, placed at the thematic center of the emblem sequence in Emblem XXVI where Maier defines the essence of true alchemy as cognitionem chymiae cum praxi, knowledge of chemistry joined with practice. De Jong identifies the unusually dense scriptural marginalia surrounding Emblem XXVI as evidence that Maier deliberately foregrounds the religious-sapiential basis of the entire alchemical enterprise at the midpoint of his work. The Solomonic wisdom tradition, transmitted through the Rosarium Philosophorum and the Aurora Consurgens, provides the framework: Wisdom is the tree of life accessible to the pure of heart, and the alchemical Work is a form of participation in divine creative knowledge. De Jong reads Emblem XXVI and its companion Emblem XXVII as Maier's philosophical manifesto within the larger emblematic program, asserting that alchemy is not mere metalworking but a branch of sacred knowledge continuous with biblical and patristic Wisdom literature. The insistence on joining knowledge with practice distinguishes Maier's sapiential ideal from purely contemplative philosophy: true wisdom is verified only through the successful completion of the Work."
    ),
    (
        "secretum-nobilissimorum",
        "The Secretum Nobilissimorum is a sixteenth-century alchemical text by Jodocus Greverus containing allegorical readings of classical myths as encoded alchemical teachings, including an interpretation of the Atalanta-Hippomenes footrace that provides one of the direct precedents for Maier's central conceit. De Jong identifies Greverus alongside Robertus Vallensis as a source for the frontispiece commentary of Atalanta Fugiens, where the two authorities together establish the hermeneutic tradition of reading Ovid's myth as a technical allegory of the volatile-fixed dynamic in the Great Work. Greverus's contribution lies in consolidating the method of systematic mythological-alchemical interpretation that Maier would bring to its fullest expression in both Atalanta Fugiens and Arcana Arcanissima. The text belongs to the sixteenth-century tradition of alchemical-mythological commentaries that drew on earlier medieval precedents, including Petrus Bonus's claim that classical poets transmitted hermetic wisdom in encoded form. De Jong's identification of Greverus as a direct source demonstrates that even Maier's most original-seeming allegorical moves have traceable textual genealogies."
    ),
    (
        "sol",
        "Sol, gold, and the Sun form the masculine, active, hot, and dry pole of the alchemical binary system, representing the fixed principle that seeks union with its volatile lunar counterpart throughout the stages of the Great Work. De Jong demonstrates that Maier's Sol operates simultaneously on three levels: as the metal gold that is the goal and the seed of the Work, as the celestial Sun that governs the ripening of metals in the earth, and as the philosophical principle of fixity, activity, and masculine generative power. In De Circulo Physico Quadrato, Maier establishes a circular concordance between the human heart as the center of the body, gold as the perfect center among the metals, and the Sun as the center of the planetary system, with God providing the ultimate source of strength that flows through all three. In the frontispiece of Atalanta Fugiens, the solar principle appears as Hippomenes carrying the golden apples, while in the emblem sequence Sol is figured through the King, the wingless bird, and the fixed masculine partner in every coniunctio scene. De Jong traces the Jabir ibn Hayyan tradition in which sulphur represents the hot and dry properties that must be balanced with mercury's cold and moist to produce the perfected metal."
    ),
    (
        "solutio",
        "Solutio, the dissolving of a solid substance into a liquid or undifferentiated state, is one of the two master operations of the alchemical art, paired with coagulatio in the fundamental formula solve et coagula. The Turba Philosophorum teaches that every dissolution is a mortification (killing) and every coagulation a vivification (enlivening), establishing the principle that the dissolving of existing form is simultaneously the death of the old and the precondition for the birth of the new. De Jong traces solutio imagery throughout Atalanta Fugiens, from the immersion and drowning motifs in the King sequence to the melting and liquefaction that precede every reconstitution. In Emblem XXXI, the King swimming in the sea and calling for rescue encodes the solar principle in its dissolved state, reduced to the primary matter from which it must be extracted and reconstituted. De Jong connects Maier's solutio to the Tabula Smaragdina's injunction to separate earth from fire, the subtle from the gross, in a smooth way with great sagacity, presenting dissolution not as violent destruction but as a skilled and deliberate operation requiring the adept's full understanding of the matter's nature."
    ),
    (
        "solve-et-coagula",
        "Solve et coagula, dissolve and coagulate, is the fundamental binary rhythm of the alchemical Work, expressing the principle that all transformation proceeds through the alternation of breaking down existing forms and building up new ones from the released material. De Jong traces Maier's use of this formula to the Scalae Philosophorum, where it appears as the concise summary of the entire alchemical process, and to the Turba Philosophorum's teaching that one nature coagulates only through the dissolution of another. Maier encodes this rhythm throughout Atalanta Fugiens, from the reciprocal dissolution-coagulation of Emblem V, where the toad coagulates as the woman dissolves, to the final mutual destruction of Emblem L, where dragon and woman consume each other and all returns to primary matter. De Jong reads the alternating pattern of solve et coagula as the structural principle governing the progression of the entire emblem sequence, with each emblem depicting some aspect of the interplay between dissolution and fixation. The Merlini allegory's teaching that the king must be dissolved before he can be coagulated into a renewed form provides the narrative expression of this binary logic."
    ),
    (
        "sphinx",
        "The Sphinx of Greek mythology, the creature who posed a deadly riddle to travelers approaching Thebes and destroyed those who could not answer, was adopted by alchemists as a figure for the deliberate obscurity of their tradition, which tests the intellectual worthiness of those who seek its secrets. Maier uses the Sphinx in Emblem XXXIX as the guardian of alchemical knowledge whose riddle stands for the encoded symbolic language in which the secrets of the Art are transmitted across generations. De Jong reads this emblem as Maier's self-conscious reflection on the hermeneutic difficulty of alchemical literature, where truth is deliberately concealed behind mythological narratives, paradoxes, and contradictory formulations that only the genuinely prepared adept can penetrate. The Sphinx thus represents not an obstacle to be overcome but a necessary test that ensures the knowledge reaches only those capable of using it responsibly. De Jong connects the Sphinx motif to Maier's broader epistemological stance that the Work requires intellectual penetration of veiled symbolic language as much as practical laboratory skill, making the decoding of riddles an essential rather than ornamental dimension of alchemical practice."
    ),
    (
        "sublimatio",
        "Sublimation in the alchemical tradition is the operation of raising the volatile, spiritual component of a substance from its dense, earthy matrix through the application of heat, purifying it by separating the subtle from the gross. In Emblem XXX's comprehensive summary of the alchemical operations, Maier lists sublimatio alongside solutio, coagulatio, and the other essential stages, designating it as the most important operation in which some parts ascend and other parts descend. De Jong connects sublimation to Maier's hierarchical cosmology, where the Work proceeds by elevating base matter toward its celestial archetype, and the winged, ascending figures that recur across the emblem sequence visually encode this upward movement. The Tabula Smaragdina's teaching that the substance rises from earth to heaven and descends again to earth, receiving the force of things above and below, provides the cosmological framework for sublimation as a cosmic rather than merely technical operation. De Jong shows that for Maier, sublimation operates simultaneously in the chemical register (the physical raising of vapors), the medical register (the refinement of gross humors), and the spiritual register (the elevation of the soul from its material entanglement)."
    ),
    (
        "sulphur",
        "Sulphur in alchemical theory represents the fixed, masculine, hot, and dry principle that, combined with Mercury, constitutes the foundation of all metals, a doctrine originating with Jabir ibn Hayyan in the eighth century and transmitted to Western Europe through the Latin translations of the twelfth century. De Jong demonstrates that Maier expresses the sulphur-mercury theory in the title of his emblem book itself, where Hippomenes (Sulphur) pursues Atalanta (Mercury) in the frontispiece allegory. The various differences between metals were understood as resulting from the different proportions in which sulphur and mercury combined, with gold representing the perfect equilibrium of both principles. In Atalanta Fugiens, the wingless figures in Emblems VII and XVI represent sulphur's solar, fixed nature, while the winged counterparts represent the volatile mercury that must be captured and bonded. De Jong traces Maier's sulphur imagery through the Lullian tradition, where the Son of Philosophy is identified as 'sulphur carried in mercury,' and through the Rosarium's teaching that without the union of sulphur and mercury no tinctura can be produced."
    ),
    (
        "tabula-chimica",
        "The Tabula Chimica is a Latin translation of an Arabic alchemical text by Muhammad ibn Umail, known in the Latin West as Senior Zadith, containing visionary descriptions of the volatile and fixed principles figured as paired birds and an extended allegorical dialogue between Sun and Moon. De Jong traces the winged and wingless bird motif of Emblem VII directly to Senior Zadith's Tabula Chimica, where two birds represent the volatile Mercury and fixed Sulphur that must be bonded together for the Work to succeed. The text also provides the source for the 'Letter of the Sun to the Waxing Moon' used in Emblem XXX, where Luna declares her dependence on Sol's warmth and Sol acknowledges his need for Luna's capacity for multiplication. De Jong demonstrates that Maier consistently works through the Tabula Chimica to access the Arabic alchemical tradition, making Senior Zadith one of the most important mediating authorities in the textual genealogy of Atalanta Fugiens. The bird symbolism established by the Tabula Chimica became central to the iconographic vocabulary of the entire Western alchemical tradition, and Maier's use of it places his work squarely within this lineage."
    ),
    (
        "tabula-smaragdina",
        "The Tabula Smaragdina or Emerald Tablet is the foundational text of the Hermetic tradition, a brief and enigmatic composition attributed to Hermes Trismegistus that encapsulates the entire philosophy of alchemy in a few dense sentences, beginning with the axiom that what is below is like what is above. De Jong traces the earliest known manuscript to the work of Jabir ibn Hayyan in the eighth century, while legends attribute its discovery to Sarah wife of Abraham finding an emerald table inscribed with the text in the tomb of Hermes Trismegistus. Maier opens Atalanta Fugiens by deriving the mottos of Emblems I and II directly from the Tabula, establishing the Hermetic cosmological framework as the foundation for the entire work. De Jong reads this deliberate placement as a programmatic statement of allegiance: Maier signals from the outset that his emblem book operates within the Hermetic tradition of correspondences between heaven and earth, macrocosm and microcosm. The Tabula's description of a substance whose father is the Sun and whose mother is the Moon, carried by the wind in its belly and nursed by the Earth, provides the archetypal model for the cosmological framework that structures all fifty emblems."
    ),
    (
        "tinctura",
        "The Tincture in alchemical usage designates the coloring agent of transmutation, the active principle within the perfected Philosopher's Stone that imparts the golden or red color to base metal, transforming it permanently. The concept originates in the ancient connection between alchemy and the dyeing arts, where the ability to permanently stain a material with a new color was understood as a model for the permanent transformation of metals. De Jong connects the Tincture to the dyeing metaphor of Emblem III, where the washing and bleaching operations prepare matter to receive the final color, just as textiles had to be thoroughly cleansed before entering the dye bath. The Rosarium Philosophorum teaches that without the union of Sol and Luna there would be no tinctura, and that even if one existed without the other, it would have no coloring power. De Jong shows that for Maier the tinctura rubea represents the culminating achievement of the Great Work, the moment when the color of perfection is permanently fixed in the substance, as evidenced by King Duenech's cheeks being 'coloured rose-red' in the epigram of Emblem XLVIII."
    ),
    (
        "tractatulus-de-practica-lapidis",
        "The Tractatulus de Practica Lapidis Philosophici is a short Latin alchemical treatise falsely attributed to Aristotle, transmitted through the Artis Auriferae compilation, which describes the preparation of the Philosopher's Stone through the union and mutual transformation of elemental principles. De Jong identifies this pseudo-Aristotelian text as the direct motto source for two of Maier's most important early emblems: Emblem IV, whose brother-sister marriage imagery encodes the union of complementary elemental natures, and Emblem V, whose striking image of a toad suckling at a woman's breast until both are transformed derives directly from this source. The attribution to Aristotle, though spurious, lent the text considerable authority in the medieval and Renaissance alchemical tradition, and its placement in the Artis Auriferae ensured its wide circulation among practitioners. De Jong's source identification demonstrates that Maier's most vivid and apparently original emblematic conceits often have precise textual genealogies in the compilation literature. The Tractatulus's teaching on elemental union through mutual transformation provides the doctrinal basis for Maier's recurring theme that one nature can only be changed through the complementary action of its opposite."
    ),
    (
        "tria-prima",
        "The Tria Prima or three principles of Mercury, Sulphur, and Salt constitute the Paracelsian revision of traditional alchemical theory, expanding the classical two-principle system of Mercury and Sulphur by adding Salt as a third term corresponding to the body, while Mercury corresponds to spirit and Sulphur to soul. Paracelsus introduced this tripartite framework in the early sixteenth century as part of his broader reform of medicine and natural philosophy, and it rapidly became one of the dominant theoretical models in alchemical literature. However, Tilton argues that reducing Emblem XXI's geometric formula to a straightforward Paracelsian reading misses the deeper complexity of Maier's engagement with the alchemical tradition, since the triangle in Emblem XXI represents body, spirit, and soul in terms that draw more directly on the Rosarium Philosophorum and pre-Paracelsian Aristotelian elemental transmutation. De Jong's analysis supports a nuanced reading: while the tria prima are acknowledged in the discourse of Emblem XXI, Maier positions his work within a lineage of alchemical thought that predates and exceeds the Paracelsian framework. The contested status of the tria prima in the scholarship on Atalanta Fugiens reflects a genuine ambiguity in Maier's own intellectual positioning between traditional and reformed alchemy."
    ),
    (
        "turba-philosophorum",
        "The Turba Philosophorum or Assembly of Philosophers is a major alchemical compilation of Arabic origin, structured as a dialogue among ancient Greek philosophers debating the principles of the Art, and constituting the single most frequently cited source in Atalanta Fugiens. De Jong attributes nine emblem mottos to the Turba, more than from any other single text, with its influence particularly prominent in the washing emblems (Emblem III), the hermaphrodite sequence (Emblem XXXIII), and the culminating Emblem L where Theophilus's teaching on mutual destruction provides the final image. The compilation's dialogic structure, in which figures such as Pythagoras, Socrates, and Arisleus debate the nature of the Work, established a model of knowledge as collective inquiry that resonates with Maier's own multi-perspectival approach in Atalanta Fugiens. De Jong traces the Turba's transmission from its Arabic origins through the Latin translations that made it available in the compilation volumes of the Artis Auriferae and Theatrum Chemicum, demonstrating its status as a foundational reference work for the entire Western alchemical tradition. The Turba's core teaching that one nature coagulates only through the dissolution of another provides the doctrinal formula that Maier dramatizes throughout his emblem sequence."
    ),
    (
        "typhon",
        "Typhon, the Egyptian figure of destruction who murders and dismembers Osiris in the mythological cycle narrated by Plutarch, was adopted by alchemists as a personification of the corrosive, fiery agent of dissolution that breaks down the existing solar form as a prerequisite for its reconstitution. De Jong reads Maier's use of Typhon in Emblem XLIV as the destructive complement to Isis's restorative role: where Isis gathers and reassembles, Typhon scatters and destroys, and both functions are necessary for the completion of the Work. In alchemical terms, Typhon represents the agent of the nigredo, the corrosive force that reduces the solar principle to its dismembered, dissolved state, from which Isis (the lunar, feminine restorative agent) can reconstruct it in perfected form. De Jong connects Typhon's violence to the broader principle that operates throughout the emblem sequence: the most complete destruction is the prerequisite for the most complete renewal. Maier's treatment of Typhon as a necessary rather than purely malevolent force distinguishes the alchemical reading from the moral interpretation, where the Work requires destruction as the gateway to perfection."
    ),
    (
        "vas-hermeticum",
        "The Vas Hermeticum or hermetically sealed vessel is the operational prerequisite for the entire alchemical Work, the closed container within which all transformations occur and from which no volatile spirit can escape during the processes of heating, dissolution, and reconstitution. The term 'hermetic' itself derives from Hermes Trismegistus, connecting the practical technique of sealing the vessel to the mythological founder of the entire alchemical tradition. De Jong identifies the vas hermeticum in Maier's philosophical egg of Emblem VIII and in the enclosed spaces where transformations occur throughout the emblem sequence, arguing that the vessel's perfect seal is what distinguishes the alchemist's controlled transformation from the uncontrolled decomposition of ordinary nature. The requirement for hermetic sealing reflects a core alchemical principle: the Work must proceed within a self-contained system that mirrors the cosmos, where nothing is lost and everything circulates. De Jong shows that for Maier the vessel is both practical apparatus and metaphysical concept, since the sealed space of the vas hermeticum recreates the conditions of the cosmic egg from which creation originally emerged."
    ),
    (
        "venus",
        "Venus in Maier's alchemical program is the divine agent who makes the union of volatile and fixed possible, appearing in the frontispiece as the goddess who provides Hippomenes with the three golden apples without which his pursuit of Atalanta would be futile. De Jong reads Venus as Maier's figure for the art or technique of alchemy itself: the catalytic principle that enables the adept to fix the volatile, making her the patron of the entire enterprise rather than simply another mythological character. In Emblem XLI, Venus rushes to the dying Adonis and stains the white roses red with her blood, an image De Jong connects to the transition from albedo to rubedo, where the feminine principle's sacrifice effects the final coloring of the Stone. The Rosarium Philosophorum's rose-garden imagery, which provides the source for this emblem, identifies Venus's blood with the tinctura rubea that transforms white matter into red. De Jong demonstrates that Venus operates at the intersection of the erotic, the agricultural, and the alchemical in Atalanta Fugiens: as goddess of love she drives the union of opposites, as patroness of gardens she oversees the cultivation of the philosophical seed, and as provider of the golden apples she supplies the catalytic art without which nature cannot be perfected."
    ),
    (
        "white-lead",
        "White lead or plumbum album in alchemical usage designates the purified white substrate produced by the albedo stage, the receptive ground into which the seed of philosophical gold must be sown for the Work to advance toward its final reddening. De Jong traces the concept through Maier's Emblem VI, where the extended agricultural analogy of sowing gold in white foliated earth draws on the Rosarium Philosophorum's teaching and the Turba's instruction about the systematic arrangement of white lead. The term carries a double reference: in the practical register, white lead is the oxide of lead (ceruse), a white powder produced by the chemical alteration of the base metal Saturn (lead), which embodies the transformation from dark, heavy impurity to purified whiteness. De Jong shows that Maier connects this chemical process to the planetary mythology, where Saturn (lead, blackness, melancholy) must give way to Jupiter and eventually to the whiteness of Diana before the reddening can occur. The achievement of white lead thus marks the critical transition from nigredo to albedo, represented in Emblem XXII by the instruction to throw snow in the black face of Saturn, and signaling that the matter is ready to receive the final tincture."
    ),
]


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA journal_mode=WAL")

    updated = 0
    skipped = 0
    not_found = 0

    for slug, definition_long in DEFINITIONS:
        # Check if row exists and definition_long is NULL
        row = conn.execute(
            "SELECT definition_long FROM dictionary_terms WHERE slug = ?",
            (slug,)
        ).fetchone()

        if row is None:
            print(f"  NOT FOUND: {slug}")
            not_found += 1
            continue

        if row[0] is not None:
            print(f"  SKIPPED (already set): {slug}")
            skipped += 1
            continue

        conn.execute(
            "UPDATE dictionary_terms SET definition_long = ? WHERE slug = ?",
            (definition_long, slug)
        )
        updated += 1
        print(f"  UPDATED: {slug}")

    conn.commit()

    # Verify
    total_null = conn.execute(
        "SELECT COUNT(*) FROM dictionary_terms WHERE definition_long IS NULL"
    ).fetchone()[0]
    total = conn.execute("SELECT COUNT(*) FROM dictionary_terms").fetchone()[0]

    conn.close()

    print(f"\n--- Results ---")
    print(f"Updated: {updated}")
    print(f"Skipped (already set): {skipped}")
    print(f"Not found: {not_found}")
    print(f"Remaining NULL: {total_null}/{total}")


if __name__ == "__main__":
    main()
